
diff --git a/kernel/
diff --git a/kernel/irq
diff --git a/kernel/time
diff --git a/kernel/trace
diff --git a/kernel/gcov
diff --git a/kernel/sched
diff --git a/kernel/events
diff --git a/kernel/power
diff --git a/kernel/debug
diff --git a/kernel/debug/kdb
diff --git a/scripts
diff --git a/scripts/dtc
diff --git a/scripts/dtc/libfdt
diff --git a/scripts/mod
diff --git a/scripts/basic
diff --git a/scripts/mkqcdtbootimg
diff --git a/scripts/mkqcdtbootimg/mincrypt
diff --git a/scripts/rt-tester
diff --git a/scripts/kconfig
diff --git a/scripts/kconfig/lxdialog
diff --git a/scripts/selinux
diff --git a/scripts/selinux/mdp
diff --git a/scripts/selinux/genheaders
diff --git a/scripts/tracing
diff --git a/scripts/coccinelle
diff --git a/scripts/coccinelle/api
diff --git a/scripts/coccinelle/api/alloc
diff --git a/scripts/coccinelle/iterators
diff --git a/scripts/coccinelle/misc
diff --git a/scripts/coccinelle/tests
diff --git a/scripts/coccinelle/free
diff --git a/scripts/coccinelle/locks
diff --git a/scripts/coccinelle/null
diff --git a/scripts/ksymoops
diff --git a/scripts/package
diff --git a/scripts/genksyms
diff --git a/mm
diff --git a/arch
diff --git a/arch/sparc
diff --git a/arch/sparc/kernel
diff --git a/arch/sparc/mm
diff --git a/arch/sparc/math-emu
diff --git a/arch/sparc/lib
diff --git a/arch/sparc/configs
diff --git a/arch/sparc/oprofile
diff --git a/arch/sparc/boot
diff --git a/arch/sparc/prom
diff --git a/arch/sparc/include
diff --git a/arch/sparc/include/asm
diff --git a/arch/arm
diff --git a/arch/arm/mach-msm
diff --git a/arch/arm/mach-msm/qdsp6v2
diff --git a/arch/arm/mach-msm/qdsp6v2/ultrasound
diff --git a/arch/arm/mach-msm/qdsp6v2/ultrasound/version_b
diff --git a/arch/arm/mach-msm/qdsp6v2/ultrasound/version_a
diff --git a/arch/arm/mach-msm/msm_bus
diff --git a/arch/arm/mach-msm/include
diff --git a/arch/arm/mach-msm/include/mach
diff --git a/arch/arm/mach-msm/include/mach/qdsp6v2
diff --git a/arch/arm/common
diff --git a/arch/arm/mach-davinci
diff --git a/arch/arm/mach-davinci/include
diff --git a/arch/arm/mach-davinci/include/mach
diff --git a/arch/arm/mach-orion5x
diff --git a/arch/arm/mach-orion5x/include
diff --git a/arch/arm/mach-orion5x/include/mach
diff --git a/arch/arm/mach-ks8695
diff --git a/arch/arm/mach-ks8695/include
diff --git a/arch/arm/mach-ks8695/include/mach
diff --git a/arch/arm/mach-w90x900
diff --git a/arch/arm/mach-w90x900/include
diff --git a/arch/arm/mach-w90x900/include/mach
diff --git a/arch/arm/mach-ux500
diff --git a/arch/arm/mach-ux500/include
diff --git a/arch/arm/mach-ux500/include/mach
diff --git a/arch/arm/mach-omap2
diff --git a/arch/arm/mach-omap2/include
diff --git a/arch/arm/mach-omap2/include/mach
diff --git a/arch/arm/kernel
diff --git a/arch/arm/mach-spear3xx
diff --git a/arch/arm/mach-spear3xx/include
diff --git a/arch/arm/mach-spear3xx/include/mach
diff --git a/arch/arm/plat-iop
diff --git a/arch/arm/mach-mxs
diff --git a/arch/arm/mach-mxs/devices
diff --git a/arch/arm/mach-mxs/include
diff --git a/arch/arm/mach-mxs/include/mach
diff --git a/arch/arm/mvp
diff --git a/arch/arm/mvp/mvpkm
diff --git a/arch/arm/mvp/pvtcpkm
diff --git a/arch/arm/mvp/commkm
diff --git a/arch/arm/mvp/oektestkm
diff --git a/arch/arm/mach-ixp4xx
diff --git a/arch/arm/mach-ixp4xx/include
diff --git a/arch/arm/mach-ixp4xx/include/mach
diff --git a/arch/arm/mach-ebsa110
diff --git a/arch/arm/mach-ebsa110/include
diff --git a/arch/arm/mach-ebsa110/include/mach
diff --git a/arch/arm/mach-s3c24xx
diff --git a/arch/arm/mach-s3c24xx/include
diff --git a/arch/arm/mach-s3c24xx/include/mach
diff --git a/arch/arm/mach-zynq
diff --git a/arch/arm/mach-zynq/include
diff --git a/arch/arm/mach-zynq/include/mach
diff --git a/arch/arm/mach-lpc32xx
diff --git a/arch/arm/mach-lpc32xx/include
diff --git a/arch/arm/mach-lpc32xx/include/mach
diff --git a/arch/arm/mm
diff --git a/arch/arm/mach-u300
diff --git a/arch/arm/mach-u300/include
diff --git a/arch/arm/mach-u300/include/mach
diff --git a/arch/arm/mach-ixp23xx
diff --git a/arch/arm/mach-ixp23xx/include
diff --git a/arch/arm/mach-ixp23xx/include/mach
diff --git a/arch/arm/mach-prima2
diff --git a/arch/arm/mach-prima2/include
diff --git a/arch/arm/mach-prima2/include/mach
diff --git a/arch/arm/plat-omap
diff --git a/arch/arm/plat-omap/include
diff --git a/arch/arm/plat-omap/include/plat
diff --git a/arch/arm/plat-spear
diff --git a/arch/arm/plat-spear/include
diff --git a/arch/arm/plat-spear/include/plat
diff --git a/arch/arm/plat-nomadik
diff --git a/arch/arm/plat-nomadik/include
diff --git a/arch/arm/plat-nomadik/include/plat
diff --git a/arch/arm/mach-s3c2440
diff --git a/arch/arm/mach-vexpress
diff --git a/arch/arm/mach-vexpress/include
diff --git a/arch/arm/mach-vexpress/include/mach
diff --git a/arch/arm/mach-integrator
diff --git a/arch/arm/mach-integrator/include
diff --git a/arch/arm/mach-integrator/include/mach
diff --git a/arch/arm/mach-s5pc100
diff --git a/arch/arm/mach-s5pc100/include
diff --git a/arch/arm/mach-s5pc100/include/mach
diff --git a/arch/arm/net
diff --git a/arch/arm/mach-shmobile
diff --git a/arch/arm/mach-shmobile/include
diff --git a/arch/arm/mach-shmobile/include/mach
diff --git a/arch/arm/mach-picoxcell
diff --git a/arch/arm/mach-picoxcell/include
diff --git a/arch/arm/mach-picoxcell/include/mach
diff --git a/arch/arm/mach-spear6xx
diff --git a/arch/arm/mach-spear6xx/include
diff --git a/arch/arm/mach-spear6xx/include/mach
diff --git a/arch/arm/plat-mxc
diff --git a/arch/arm/plat-mxc/devices
diff --git a/arch/arm/plat-mxc/include
diff --git a/arch/arm/plat-mxc/include/mach
diff --git a/arch/arm/plat-pxa
diff --git a/arch/arm/plat-pxa/include
diff --git a/arch/arm/plat-pxa/include/plat
diff --git a/arch/arm/mach-s5p64x0
diff --git a/arch/arm/mach-s5p64x0/include
diff --git a/arch/arm/mach-s5p64x0/include/mach
diff --git a/arch/arm/mach-exynos
diff --git a/arch/arm/mach-exynos/include
diff --git a/arch/arm/mach-exynos/include/mach
diff --git a/arch/arm/mach-pnx4008
diff --git a/arch/arm/mach-pnx4008/include
diff --git a/arch/arm/mach-pnx4008/include/mach
diff --git a/arch/arm/mach-h720x
diff --git a/arch/arm/mach-h720x/include
diff --git a/arch/arm/mach-h720x/include/mach
diff --git a/arch/arm/plat-versatile
diff --git a/arch/arm/plat-versatile/include
diff --git a/arch/arm/plat-versatile/include/plat
diff --git a/arch/arm/mach-cns3xxx
diff --git a/arch/arm/mach-cns3xxx/include
diff --git a/arch/arm/mach-cns3xxx/include/mach
diff --git a/arch/arm/mach-dove
diff --git a/arch/arm/mach-dove/include
diff --git a/arch/arm/mach-dove/include/mach
diff --git a/arch/arm/lib
diff --git a/arch/arm/mach-pxa
diff --git a/arch/arm/mach-pxa/include
diff --git a/arch/arm/mach-pxa/include/mach
diff --git a/arch/arm/mach-realview
diff --git a/arch/arm/mach-realview/include
diff --git a/arch/arm/mach-realview/include/mach
diff --git a/arch/arm/plat-orion
diff --git a/arch/arm/plat-orion/include
diff --git a/arch/arm/plat-orion/include/plat
diff --git a/arch/arm/mach-kirkwood
diff --git a/arch/arm/mach-kirkwood/include
diff --git a/arch/arm/mach-kirkwood/include/mach
diff --git a/arch/arm/perfmon
diff --git a/arch/arm/mach-imx
diff --git a/arch/arm/mach-imx/include
diff --git a/arch/arm/mach-imx/include/mach
diff --git a/arch/arm/mach-netx
diff --git a/arch/arm/mach-netx/include
diff --git a/arch/arm/mach-netx/include/mach
diff --git a/arch/arm/configs
diff --git a/arch/arm/mach-iop32x
diff --git a/arch/arm/mach-iop32x/include
diff --git a/arch/arm/mach-iop32x/include/mach
diff --git a/arch/arm/mach-shark
diff --git a/arch/arm/mach-shark/include
diff --git a/arch/arm/mach-shark/include/mach
diff --git a/arch/arm/mach-iop13xx
diff --git a/arch/arm/mach-iop13xx/include
diff --git a/arch/arm/mach-iop13xx/include/mach
diff --git a/arch/arm/mach-footbridge
diff --git a/arch/arm/mach-footbridge/include
diff --git a/arch/arm/mach-footbridge/include/mach
diff --git a/arch/arm/mach-nomadik
diff --git a/arch/arm/mach-nomadik/include
diff --git a/arch/arm/mach-nomadik/include/mach
diff --git a/arch/arm/nwfpe
diff --git a/arch/arm/oprofile
diff --git a/arch/arm/tools
diff --git a/arch/arm/crypto
diff --git a/arch/arm/mach-rpc
diff --git a/arch/arm/mach-rpc/include
diff --git a/arch/arm/mach-rpc/include/mach
diff --git a/arch/arm/mach-iop33x
diff --git a/arch/arm/mach-iop33x/include
diff --git a/arch/arm/mach-iop33x/include/mach
diff --git a/arch/arm/mach-omap1
diff --git a/arch/arm/mach-omap1/include
diff --git a/arch/arm/mach-omap1/include/mach
diff --git a/arch/arm/mach-versatile
diff --git a/arch/arm/mach-versatile/include
diff --git a/arch/arm/mach-versatile/include/mach
diff --git a/arch/arm/mach-s3c64xx
diff --git a/arch/arm/mach-s3c64xx/include
diff --git a/arch/arm/mach-s3c64xx/include/mach
diff --git a/arch/arm/mach-highbank
diff --git a/arch/arm/mach-highbank/include
diff --git a/arch/arm/mach-highbank/include/mach
diff --git a/arch/arm/plat-samsung
diff --git a/arch/arm/plat-samsung/include
diff --git a/arch/arm/plat-samsung/include/plat
diff --git a/arch/arm/mach-mmp
diff --git a/arch/arm/mach-mmp/include
diff --git a/arch/arm/mach-mmp/include/mach
diff --git a/arch/arm/plat-s5p
diff --git a/arch/arm/plat-s3c24xx
diff --git a/arch/arm/vfp
diff --git a/arch/arm/mach-bcmring
diff --git a/arch/arm/mach-bcmring/csp
diff --git a/arch/arm/mach-bcmring/csp/tmr
diff --git a/arch/arm/mach-bcmring/csp/dmac
diff --git a/arch/arm/mach-bcmring/csp/chipc
diff --git a/arch/arm/mach-bcmring/include
diff --git a/arch/arm/mach-bcmring/include/mach
diff --git a/arch/arm/mach-bcmring/include/mach/csp
diff --git a/arch/arm/mach-bcmring/include/csp
diff --git a/arch/arm/mach-at91
diff --git a/arch/arm/mach-at91/include
diff --git a/arch/arm/mach-at91/include/mach
diff --git a/arch/arm/mach-ep93xx
diff --git a/arch/arm/mach-ep93xx/include
diff --git a/arch/arm/mach-ep93xx/include/mach
diff --git a/arch/arm/boot
diff --git a/arch/arm/boot/dts
diff --git a/arch/arm/boot/dts/msm8974
diff --git a/arch/arm/boot/dts/msm8974/testcases
diff --git a/arch/arm/boot/dts/msm8974pro
diff --git a/arch/arm/boot/dts/msm8974pro/testcases
diff --git a/arch/arm/boot/dts/msm8974pro/core
diff --git a/arch/arm/boot/dts/msm8226
diff --git a/arch/arm/boot/dts/msm8226/testcases
diff --git a/arch/arm/boot/dts/msm8610
diff --git a/arch/arm/boot/dts/msm8610/testcases
diff --git a/arch/arm/boot/bootp
diff --git a/arch/arm/boot/compressed
diff --git a/arch/arm/mach-ixp2000
diff --git a/arch/arm/mach-ixp2000/include
diff --git a/arch/arm/mach-ixp2000/include/mach
diff --git a/arch/arm/mach-sa1100
diff --git a/arch/arm/mach-sa1100/include
diff --git a/arch/arm/mach-sa1100/include/mach
diff --git a/arch/arm/mach-clps711x
diff --git a/arch/arm/mach-clps711x/include
diff --git a/arch/arm/mach-clps711x/include/mach
diff --git a/arch/arm/mach-mv78xx0
diff --git a/arch/arm/mach-mv78xx0/include
diff --git a/arch/arm/mach-mv78xx0/include/mach
diff --git a/arch/arm/include
diff --git a/arch/arm/include/asm
diff --git a/arch/arm/include/asm/hardware
diff --git a/arch/arm/include/asm/mach
diff --git a/arch/arm/mach-tegra
diff --git a/arch/arm/mach-tegra/include
diff --git a/arch/arm/mach-tegra/include/mach
diff --git a/arch/arm/mach-l7200
diff --git a/arch/arm/mach-l7200/include
diff --git a/arch/arm/mach-l7200/include/mach
diff --git a/arch/arm/mach-gemini
diff --git a/arch/arm/mach-gemini/include
diff --git a/arch/arm/mach-gemini/include/mach
diff --git a/arch/arm/mach-s5pv210
diff --git a/arch/arm/mach-s5pv210/include
diff --git a/arch/arm/mach-s5pv210/include/mach
diff --git a/arch/arm/mach-s3c2412
diff --git a/arch/arm/mach-s3c2410
diff --git a/arch/arm/mach-vt8500
diff --git a/arch/arm/mach-vt8500/include
diff --git a/arch/arm/mach-vt8500/include/mach
diff --git a/arch/tile
diff --git a/arch/tile/kernel
diff --git a/arch/tile/mm
diff --git a/arch/tile/lib
diff --git a/arch/tile/configs
diff --git a/arch/tile/kvm
diff --git a/arch/tile/include
diff --git a/arch/tile/include/arch
diff --git a/arch/tile/include/asm
diff --git a/arch/tile/include/hv
diff --git a/block
diff --git a/block/partitions
diff --git a/drivers
diff --git a/drivers/vhost
diff --git a/drivers/remoteproc
diff --git a/drivers/gpu
diff --git a/drivers/gpu/ion
diff --git a/drivers/gpu/ion/msm
diff --git a/drivers/gpu/ion/tegra
diff --git a/drivers/gpu/msm
diff --git a/drivers/gpu/stub
diff --git a/drivers/gpu/drm
diff --git a/drivers/gpu/drm/exynos
diff --git a/drivers/gpu/drm/vmwgfx
diff --git a/drivers/gpu/drm/via
diff --git a/drivers/gpu/drm/gma500
diff --git a/drivers/gpu/drm/i2c
diff --git a/drivers/gpu/drm/mga
diff --git a/drivers/gpu/drm/udl
diff --git a/drivers/gpu/drm/nouveau
diff --git a/drivers/gpu/drm/sis
diff --git a/drivers/gpu/drm/r128
diff --git a/drivers/gpu/drm/savage
diff --git a/drivers/gpu/drm/i810
diff --git a/drivers/gpu/drm/ttm
diff --git a/drivers/gpu/drm/radeon
diff --git a/drivers/gpu/drm/radeon/reg_srcs
diff --git a/drivers/gpu/drm/i915
diff --git a/drivers/gpu/drm/tdfx
diff --git a/drivers/gpu/gpu_sysfs
diff --git a/drivers/gpu/vga
diff --git a/drivers/gud
diff --git a/drivers/gud/MobiCoreKernelApi
diff --git a/drivers/gud/MobiCoreKernelApi/public
diff --git a/drivers/gud/MobiCoreKernelApi/include
diff --git a/drivers/gud/MobiCoreDriver
diff --git a/drivers/gud/MobiCoreDriver/platforms
diff --git a/drivers/gud/MobiCoreDriver/platforms/MSM8960_SURF_STD
diff --git a/drivers/gud/MobiCoreDriver/public
diff --git a/drivers/dma
diff --git a/drivers/dma/ioat
diff --git a/drivers/dma/ipu
diff --git a/drivers/dma/ppc4xx
diff --git a/drivers/usb
diff --git a/drivers/usb/core
diff --git a/drivers/usb/musb
diff --git a/drivers/usb/atm
diff --git a/drivers/usb/notify
diff --git a/drivers/usb/serial
diff --git a/drivers/usb/otg
diff --git a/drivers/usb/wusbcore
diff --git a/drivers/usb/early
diff --git a/drivers/usb/mon
diff --git a/drivers/usb/gadget
diff --git a/drivers/usb/host
diff --git a/drivers/usb/host/whci
diff --git a/drivers/usb/host/pehci
diff --git a/drivers/usb/host/pehci/hal
diff --git a/drivers/usb/host/pehci/host
diff --git a/drivers/usb/class
diff --git a/drivers/usb/image
diff --git a/drivers/usb/renesas_usbhs
diff --git a/drivers/usb/storage
diff --git a/drivers/usb/c67x00
diff --git a/drivers/usb/misc
diff --git a/drivers/usb/misc/sisusbvga
diff --git a/drivers/usb/dwc3
diff --git a/drivers/clk
diff --git a/drivers/coresight
diff --git a/drivers/auxdisplay
diff --git a/drivers/of
diff --git a/drivers/slimbus
diff --git a/drivers/battery
diff --git a/drivers/input
diff --git a/drivers/input/joystick
diff --git a/drivers/input/joystick/iforce
diff --git a/drivers/input/tablet
diff --git a/drivers/input/touchscreen
diff --git a/drivers/input/touchscreen/mxt1188s
diff --git a/drivers/input/touchscreen/cyttsp4
diff --git a/drivers/input/touchscreen/stm_s
diff --git a/drivers/input/touchscreen/imagis
diff --git a/drivers/input/touchscreen/gt9xx
diff --git a/drivers/input/touchscreen/synaptics_s5000
diff --git a/drivers/input/touchscreen/melfas_mms136
diff --git a/drivers/input/touchscreen/synaptics_jsglte
diff --git a/drivers/input/touchscreen/cyttsp5
diff --git a/drivers/input/touchscreen/synaptics
diff --git a/drivers/input/touchscreen/synaptics/Multiverse
diff --git a/drivers/input/touchscreen/wacom
diff --git a/drivers/input/touchscreen/wacom/table
diff --git a/drivers/input/touchscreen/wacom/table/msm8974
diff --git a/drivers/input/touchscreen/wacom_hl
diff --git a/drivers/input/touchscreen/stm_fts
diff --git a/drivers/input/touchscreen/synaptics_patek
diff --git a/drivers/input/keyboard
diff --git a/drivers/input/keyboard/cypress_touchkey_s3
diff --git a/drivers/input/keyboard/cypress_touchkey_hl
diff --git a/drivers/input/keyboard/cypress_touchkey_he
diff --git a/drivers/input/keyboard/cypress_touchkey_ks01
diff --git a/drivers/input/keyboard/cypress_touchkey
diff --git a/drivers/input/keyboard/cypress_touchkey_h
diff --git a/drivers/input/keyboard/cypress_touchkey_c
diff --git a/drivers/input/gameport
diff --git a/drivers/input/mouse
diff --git a/drivers/input/misc
diff --git a/drivers/input/serio
diff --git a/drivers/bcma
diff --git a/drivers/sbus
diff --git a/drivers/sbus/char
diff --git a/drivers/md
diff --git a/drivers/md/persistent-data
diff --git a/drivers/sensors
diff --git a/drivers/sensors/yas532
diff --git a/drivers/mtd
diff --git a/drivers/mtd/lpddr
diff --git a/drivers/mtd/nand
diff --git a/drivers/mtd/nand/gpmi-nand
diff --git a/drivers/mtd/onenand
diff --git a/drivers/mtd/maps
diff --git a/drivers/mtd/devices
diff --git a/drivers/mtd/chips
diff --git a/drivers/mtd/ubi
diff --git a/drivers/mtd/tests
diff --git a/drivers/ata
diff --git a/drivers/atm
diff --git a/drivers/felica
diff --git a/drivers/parport
diff --git a/drivers/xen
diff --git a/drivers/xen/xen-pciback
diff --git a/drivers/xen/xenfs
diff --git a/drivers/xen/xenbus
diff --git a/drivers/fingerprint
diff --git a/drivers/uwb
diff --git a/drivers/uwb/i1480
diff --git a/drivers/uwb/i1480/dfu
diff --git a/drivers/mca
diff --git a/drivers/switch
diff --git a/drivers/rapidio
diff --git a/drivers/rapidio/switches
diff --git a/drivers/rapidio/devices
diff --git a/drivers/cdrom
diff --git a/drivers/pps
diff --git a/drivers/pps/clients
diff --git a/drivers/pps/generators
diff --git a/drivers/bif
diff --git a/drivers/isdn
diff --git a/drivers/isdn/hardware
diff --git a/drivers/isdn/hardware/mISDN
diff --git a/drivers/isdn/hardware/avm
diff --git a/drivers/isdn/hardware/eicon
diff --git a/drivers/isdn/mISDN
diff --git a/drivers/isdn/pcbit
diff --git a/drivers/isdn/act2000
diff --git a/drivers/isdn/i4l
diff --git a/drivers/isdn/divert
diff --git a/drivers/isdn/capi
diff --git a/drivers/isdn/icn
diff --git a/drivers/isdn/sc
diff --git a/drivers/isdn/gigaset
diff --git a/drivers/isdn/hisax
diff --git a/drivers/isdn/hysdn
diff --git a/drivers/isdn/isdnloop
diff --git a/drivers/block
diff --git a/drivers/block/mtip32xx
diff --git a/drivers/block/xen-blkback
diff --git a/drivers/block/drbd
diff --git a/drivers/block/paride
diff --git a/drivers/block/aoe
diff --git a/drivers/dio
diff --git a/drivers/amba
diff --git a/drivers/staging
diff --git a/drivers/staging/sbe-2t3e3
diff --git a/drivers/staging/mei
diff --git a/drivers/staging/omapdrm
diff --git a/drivers/staging/et131x
diff --git a/drivers/staging/cptm1217
diff --git a/drivers/staging/usbip
diff --git a/drivers/staging/usbip/userspace
diff --git a/drivers/staging/usbip/userspace/libsrc
diff --git a/drivers/staging/usbip/userspace/src
diff --git a/drivers/staging/usbip/userspace/doc
diff --git a/drivers/staging/vme
diff --git a/drivers/staging/vme/boards
diff --git a/drivers/staging/vme/devices
diff --git a/drivers/staging/vme/bridges
diff --git a/drivers/staging/rtl8187se
diff --git a/drivers/staging/rtl8187se/ieee80211
diff --git a/drivers/staging/rtl8192e
diff --git a/drivers/staging/rtl8192e/rtl8192e
diff --git a/drivers/staging/nvec
diff --git a/drivers/staging/zram
diff --git a/drivers/staging/ste_rmi4
diff --git a/drivers/staging/gobi
diff --git a/drivers/staging/gobi/QCUSBNet2k
diff --git a/drivers/staging/keucr
diff --git a/drivers/staging/serqt_usb2
diff --git a/drivers/staging/xgifb
diff --git a/drivers/staging/iio
diff --git a/drivers/staging/iio/adc
diff --git a/drivers/staging/iio/imu
diff --git a/drivers/staging/iio/imu/mpu
diff --git a/drivers/staging/iio/imu/inv_sensors
diff --git a/drivers/staging/iio/imu/inv_mpu
diff --git a/drivers/staging/iio/imu/mpu_primary
diff --git a/drivers/staging/iio/inv_test
diff --git a/drivers/staging/iio/magnetometer
diff --git a/drivers/staging/iio/meter
diff --git a/drivers/staging/iio/dac
diff --git a/drivers/staging/iio/cdc
diff --git a/drivers/staging/iio/Documentation
diff --git a/drivers/staging/iio/Documentation/dac
diff --git a/drivers/staging/iio/dds
diff --git a/drivers/staging/iio/impedance-analyzer
diff --git a/drivers/staging/iio/trigger
diff --git a/drivers/staging/iio/addac
diff --git a/drivers/staging/iio/light
diff --git a/drivers/staging/iio/resolver
diff --git a/drivers/staging/iio/grip
diff --git a/drivers/staging/iio/accel
diff --git a/drivers/staging/iio/gyro
diff --git a/drivers/staging/serial
diff --git a/drivers/staging/tidspbridge
diff --git a/drivers/staging/tidspbridge/pmgr
diff --git a/drivers/staging/tidspbridge/core
diff --git a/drivers/staging/tidspbridge/dynload
diff --git a/drivers/staging/tidspbridge/hw
diff --git a/drivers/staging/tidspbridge/Documentation
diff --git a/drivers/staging/tidspbridge/gen
diff --git a/drivers/staging/tidspbridge/rmgr
diff --git a/drivers/staging/tidspbridge/include
diff --git a/drivers/staging/tidspbridge/include/dspbridge
diff --git a/drivers/staging/echo
diff --git a/drivers/staging/rts5139
diff --git a/drivers/staging/line6
diff --git a/drivers/staging/telephony
diff --git a/drivers/staging/sm7xx
diff --git a/drivers/staging/quatech_usb2
diff --git a/drivers/staging/octeon
diff --git a/drivers/staging/wlags49_h25
diff --git a/drivers/staging/bcm
diff --git a/drivers/staging/comedi
diff --git a/drivers/staging/comedi/kcomedilib
diff --git a/drivers/staging/comedi/drivers
diff --git a/drivers/staging/comedi/drivers/addi-data
diff --git a/drivers/staging/ft1000
diff --git a/drivers/staging/ft1000/ft1000-pcmcia
diff --git a/drivers/staging/ft1000/ft1000-usb
diff --git a/drivers/staging/sep
diff --git a/drivers/staging/speakup
diff --git a/drivers/staging/ramster
diff --git a/drivers/staging/ramster/cluster
diff --git a/drivers/staging/wlan-ng
diff --git a/drivers/staging/slicoss
diff --git a/drivers/staging/media
diff --git a/drivers/staging/media/go7007
diff --git a/drivers/staging/media/easycap
diff --git a/drivers/staging/media/lirc
diff --git a/drivers/staging/media/cxd2099
diff --git a/drivers/staging/media/dt3155v4l
diff --git a/drivers/staging/media/solo6x10
diff --git a/drivers/staging/media/as102
diff --git a/drivers/staging/vnswap
diff --git a/drivers/staging/winbond
diff --git a/drivers/staging/rtl8192u
diff --git a/drivers/staging/rtl8192u/ieee80211
diff --git a/drivers/staging/vt6656
diff --git a/drivers/staging/frontier
diff --git a/drivers/staging/quickstart
diff --git a/drivers/staging/olpc_dcon
diff --git a/drivers/staging/asus_oled
diff --git a/drivers/staging/wlags49_h2
diff --git a/drivers/staging/wlags49_h2/man
diff --git a/drivers/staging/phison
diff --git a/drivers/staging/vt6655
diff --git a/drivers/staging/cxt1e1
diff --git a/drivers/staging/rts_pstor
diff --git a/drivers/staging/android
diff --git a/drivers/staging/android/switch
diff --git a/drivers/staging/rtl8712
diff --git a/drivers/staging/ozwpan
diff --git a/drivers/staging/panel
diff --git a/drivers/staging/zcache
diff --git a/drivers/staging/crystalhd
diff --git a/drivers/staging/zsmalloc
diff --git a/drivers/qsc
diff --git a/drivers/scsi
diff --git a/drivers/scsi/osd
diff --git a/drivers/scsi/fnic
diff --git a/drivers/scsi/ufs
diff --git a/drivers/scsi/ibmvscsi
diff --git a/drivers/scsi/mvsas
diff --git a/drivers/scsi/qla2xxx
diff --git a/drivers/scsi/cxgbi
diff --git a/drivers/scsi/cxgbi/cxgb4i
diff --git a/drivers/scsi/cxgbi/cxgb3i
diff --git a/drivers/scsi/libfc
diff --git a/drivers/scsi/aic7xxx_old
diff --git a/drivers/scsi/qla4xxx
diff --git a/drivers/scsi/sym53c8xx_2
diff --git a/drivers/scsi/libsas
diff --git a/drivers/scsi/bnx2i
diff --git a/drivers/scsi/aacraid
diff --git a/drivers/scsi/pm8001
diff --git a/drivers/scsi/bnx2fc
diff --git a/drivers/scsi/aic94xx
diff --git a/drivers/scsi/lpfc
diff --git a/drivers/scsi/pcmcia
diff --git a/drivers/scsi/mpt2sas
diff --git a/drivers/scsi/mpt2sas/mpi
diff --git a/drivers/scsi/dpt
diff --git a/drivers/scsi/device_handler
diff --git a/drivers/scsi/be2iscsi
diff --git a/drivers/scsi/bfa
diff --git a/drivers/scsi/megaraid
diff --git a/drivers/scsi/arm
diff --git a/drivers/scsi/isci
diff --git a/drivers/scsi/fcoe
diff --git a/drivers/scsi/arcmsr
diff --git a/drivers/scsi/aic7xxx
diff --git a/drivers/scsi/aic7xxx/aicasm
diff --git a/drivers/spi
diff --git a/drivers/net
diff --git a/drivers/net/vmxnet3
diff --git a/drivers/net/usb
diff --git a/drivers/net/appletalk
diff --git a/drivers/net/wimax
diff --git a/drivers/net/wimax/i2400m
diff --git a/drivers/net/cris
diff --git a/drivers/net/slip
diff --git a/drivers/net/fddi
diff --git a/drivers/net/fddi/skfp
diff --git a/drivers/net/fddi/skfp/h
diff --git a/drivers/net/tokenring
diff --git a/drivers/net/hamradio
diff --git a/drivers/net/phy
diff --git a/drivers/net/wireless
diff --git a/drivers/net/wireless/ipw2x00
diff --git a/drivers/net/wireless/prism54
diff --git a/drivers/net/wireless/bcmdhd
diff --git a/drivers/net/wireless/bcmdhd/include
diff --git a/drivers/net/wireless/bcmdhd/include/devctrl_if
diff --git a/drivers/net/wireless/bcmdhd/include/proto
diff --git a/drivers/net/wireless/b43
diff --git a/drivers/net/wireless/iwlegacy
diff --git a/drivers/net/wireless/p54
diff --git a/drivers/net/wireless/zd1211rw
diff --git a/drivers/net/wireless/rtl818x
diff --git a/drivers/net/wireless/rtl818x/rtl8180
diff --git a/drivers/net/wireless/rtl818x/rtl8187
diff --git a/drivers/net/wireless/ipsecdrvtl
diff --git a/drivers/net/wireless/rt2x00
diff --git a/drivers/net/wireless/orinoco
diff --git a/drivers/net/wireless/wl1251
diff --git a/drivers/net/wireless/iwmc3200wifi
diff --git a/drivers/net/wireless/rtlwifi
diff --git a/drivers/net/wireless/rtlwifi/rtl8192de
diff --git a/drivers/net/wireless/rtlwifi/rtl8192se
diff --git a/drivers/net/wireless/rtlwifi/rtl8192ce
diff --git a/drivers/net/wireless/rtlwifi/rtl8192c
diff --git a/drivers/net/wireless/rtlwifi/rtl8192cu
diff --git a/drivers/net/wireless/libra
diff --git a/drivers/net/wireless/libertas
diff --git a/drivers/net/wireless/ath
diff --git a/drivers/net/wireless/ath/ath5k
diff --git a/drivers/net/wireless/ath/ath6kl
diff --git a/drivers/net/wireless/ath/carl9170
diff --git a/drivers/net/wireless/ath/ath9k
diff --git a/drivers/net/wireless/wcnss
diff --git a/drivers/net/wireless/mwifiex
diff --git a/drivers/net/wireless/hostap
diff --git a/drivers/net/wireless/mwlan_aarp
diff --git a/drivers/net/wireless/iwlwifi
diff --git a/drivers/net/wireless/b43legacy
diff --git a/drivers/net/wireless/libertas_tf
diff --git a/drivers/net/wireless/brcm80211
diff --git a/drivers/net/wireless/brcm80211/brcmutil
diff --git a/drivers/net/wireless/brcm80211/brcmfmac
diff --git a/drivers/net/wireless/brcm80211/brcmsmac
diff --git a/drivers/net/wireless/brcm80211/brcmsmac/phy
diff --git a/drivers/net/wireless/brcm80211/include
diff --git a/drivers/net/wireless/wl12xx
diff --git a/drivers/net/ethernet
diff --git a/drivers/net/ethernet/oki-semi
diff --git a/drivers/net/ethernet/oki-semi/pch_gbe
diff --git a/drivers/net/ethernet/atheros
diff --git a/drivers/net/ethernet/atheros/atl1c
diff --git a/drivers/net/ethernet/atheros/atl1e
diff --git a/drivers/net/ethernet/atheros/atlx
diff --git a/drivers/net/ethernet/toshiba
diff --git a/drivers/net/ethernet/nuvoton
diff --git a/drivers/net/ethernet/dlink
diff --git a/drivers/net/ethernet/rdc
diff --git a/drivers/net/ethernet/racal
diff --git a/drivers/net/ethernet/adi
diff --git a/drivers/net/ethernet/ibm
diff --git a/drivers/net/ethernet/ibm/ehea
diff --git a/drivers/net/ethernet/ibm/emac
diff --git a/drivers/net/ethernet/sfc
diff --git a/drivers/net/ethernet/msm
diff --git a/drivers/net/ethernet/8390
diff --git a/drivers/net/ethernet/apple
diff --git a/drivers/net/ethernet/cisco
diff --git a/drivers/net/ethernet/cisco/enic
diff --git a/drivers/net/ethernet/pasemi
diff --git a/drivers/net/ethernet/i825xx
diff --git a/drivers/net/ethernet/brocade
diff --git a/drivers/net/ethernet/brocade/bna
diff --git a/drivers/net/ethernet/mellanox
diff --git a/drivers/net/ethernet/mellanox/mlx4
diff --git a/drivers/net/ethernet/natsemi
diff --git a/drivers/net/ethernet/freescale
diff --git a/drivers/net/ethernet/freescale/fs_enet
diff --git a/drivers/net/ethernet/via
diff --git a/drivers/net/ethernet/dec
diff --git a/drivers/net/ethernet/dec/tulip
diff --git a/drivers/net/ethernet/adaptec
diff --git a/drivers/net/ethernet/packetengines
diff --git a/drivers/net/ethernet/ti
diff --git a/drivers/net/ethernet/faraday
diff --git a/drivers/net/ethernet/intel
diff --git a/drivers/net/ethernet/intel/e1000
diff --git a/drivers/net/ethernet/intel/ixgb
diff --git a/drivers/net/ethernet/intel/ixgbevf
diff --git a/drivers/net/ethernet/intel/e1000e
diff --git a/drivers/net/ethernet/intel/igb
diff --git a/drivers/net/ethernet/intel/igbvf
diff --git a/drivers/net/ethernet/intel/ixgbe
diff --git a/drivers/net/ethernet/xircom
diff --git a/drivers/net/ethernet/sgi
diff --git a/drivers/net/ethernet/octeon
diff --git a/drivers/net/ethernet/icplus
diff --git a/drivers/net/ethernet/broadcom
diff --git a/drivers/net/ethernet/broadcom/bnx2x
diff --git a/drivers/net/ethernet/smsc
diff --git a/drivers/net/ethernet/emulex
diff --git a/drivers/net/ethernet/emulex/benet
diff --git a/drivers/net/ethernet/xscale
diff --git a/drivers/net/ethernet/xscale/ixp2000
diff --git a/drivers/net/ethernet/davicom
diff --git a/drivers/net/ethernet/neterion
diff --git a/drivers/net/ethernet/neterion/vxge
diff --git a/drivers/net/ethernet/seeq
diff --git a/drivers/net/ethernet/chelsio
diff --git a/drivers/net/ethernet/chelsio/cxgb4
diff --git a/drivers/net/ethernet/chelsio/cxgb
diff --git a/drivers/net/ethernet/chelsio/cxgb4vf
diff --git a/drivers/net/ethernet/chelsio/cxgb3
diff --git a/drivers/net/ethernet/stmicro
diff --git a/drivers/net/ethernet/stmicro/stmmac
diff --git a/drivers/net/ethernet/amd
diff --git a/drivers/net/ethernet/cirrus
diff --git a/drivers/net/ethernet/calxeda
diff --git a/drivers/net/ethernet/tundra
diff --git a/drivers/net/ethernet/hp
diff --git a/drivers/net/ethernet/marvell
diff --git a/drivers/net/ethernet/sis
diff --git a/drivers/net/ethernet/3com
diff --git a/drivers/net/ethernet/alteon
diff --git a/drivers/net/ethernet/renesas
diff --git a/drivers/net/ethernet/xilinx
diff --git a/drivers/net/ethernet/micrel
diff --git a/drivers/net/ethernet/cadence
diff --git a/drivers/net/ethernet/sun
diff --git a/drivers/net/ethernet/myricom
diff --git a/drivers/net/ethernet/myricom/myri10ge
diff --git a/drivers/net/ethernet/qlogic
diff --git a/drivers/net/ethernet/qlogic/qlcnic
diff --git a/drivers/net/ethernet/qlogic/netxen
diff --git a/drivers/net/ethernet/qlogic/qlge
diff --git a/drivers/net/ethernet/tehuti
diff --git a/drivers/net/ethernet/nxp
diff --git a/drivers/net/ethernet/fujitsu
diff --git a/drivers/net/ethernet/realtek
diff --git a/drivers/net/ethernet/nvidia
diff --git a/drivers/net/ethernet/microchip
diff --git a/drivers/net/ethernet/silan
diff --git a/drivers/net/ethernet/aeroflex
diff --git a/drivers/net/ethernet/tile
diff --git a/drivers/net/caif
diff --git a/drivers/net/hippi
diff --git a/drivers/net/bonding
diff --git a/drivers/net/arcnet
diff --git a/drivers/net/wan
diff --git a/drivers/net/wan/lmc
diff --git a/drivers/net/can
diff --git a/drivers/net/can/usb
diff --git a/drivers/net/can/usb/peak_usb
diff --git a/drivers/net/can/sja1000
diff --git a/drivers/net/can/cc770
diff --git a/drivers/net/can/c_can
diff --git a/drivers/net/can/mscan
diff --git a/drivers/net/can/softing
diff --git a/drivers/net/dsa
diff --git a/drivers/net/hyperv
diff --git a/drivers/net/team
diff --git a/drivers/net/irda
diff --git a/drivers/net/plip
diff --git a/drivers/net/ppp
diff --git a/drivers/net/xen-netback
diff --git a/drivers/thermal
diff --git a/drivers/target
diff --git a/drivers/target/iscsi
diff --git a/drivers/target/loopback
diff --git a/drivers/target/tcm_fc
diff --git a/drivers/cpufreq
diff --git a/drivers/virt
diff --git a/drivers/video
diff --git a/drivers/video/aty
diff --git a/drivers/video/matrox
diff --git a/drivers/video/kyro
diff --git a/drivers/video/msm
diff --git a/drivers/video/msm/mdss
diff --git a/drivers/video/msm/vidc
diff --git a/drivers/video/msm/vidc/common
diff --git a/drivers/video/msm/vidc/common/dec
diff --git a/drivers/video/msm/vidc/common/init
diff --git a/drivers/video/msm/vidc/common/vcd
diff --git a/drivers/video/msm/vidc/common/enc
diff --git a/drivers/video/msm/vidc/1080p
diff --git a/drivers/video/msm/vidc/1080p/resource_tracker
diff --git a/drivers/video/msm/vidc/1080p/ddl
diff --git a/drivers/video/msm/vidc/720p
diff --git a/drivers/video/msm/vidc/720p/resource_tracker
diff --git a/drivers/video/msm/vidc/720p/ddl
diff --git a/drivers/video/msm/mhl_v2
diff --git a/drivers/video/msm/mhl_v2/sii8240
diff --git a/drivers/video/msm/mhl_v2/sii8246
diff --git a/drivers/video/msm/mhl
diff --git a/drivers/video/exynos
diff --git a/drivers/video/riva
diff --git a/drivers/video/via
diff --git a/drivers/video/mbx
diff --git a/drivers/video/mb862xx
diff --git a/drivers/video/omap2
diff --git a/drivers/video/omap2/displays
diff --git a/drivers/video/omap2/omapfb
diff --git a/drivers/video/omap2/dss
diff --git a/drivers/video/sis
diff --git a/drivers/video/geode
diff --git a/drivers/video/savage
diff --git a/drivers/video/intelfb
diff --git a/drivers/video/i810
diff --git a/drivers/video/vermilion
diff --git a/drivers/video/console
diff --git a/drivers/video/omap
diff --git a/drivers/video/nvidia
diff --git a/drivers/video/pnx4008
diff --git a/drivers/video/logo
diff --git a/drivers/video/backlight
diff --git a/drivers/firewire
diff --git a/drivers/ieee802154
diff --git a/drivers/i2c
diff --git a/drivers/i2c/muxes
diff --git a/drivers/i2c/busses
diff --git a/drivers/i2c/algos
diff --git a/drivers/parisc
diff --git a/drivers/mfd
diff --git a/drivers/pnp
diff --git a/drivers/pnp/pnpacpi
diff --git a/drivers/pnp/pnpbios
diff --git a/drivers/pnp/isapnp
diff --git a/drivers/hid
diff --git a/drivers/hid/usbhid
diff --git a/drivers/ide
diff --git a/drivers/ssb
diff --git a/drivers/infiniband
diff --git a/drivers/infiniband/core
diff --git a/drivers/infiniband/hw
diff --git a/drivers/infiniband/hw/nes
diff --git a/drivers/infiniband/hw/ehca
diff --git a/drivers/infiniband/hw/mlx4
diff --git a/drivers/infiniband/hw/ipath
diff --git a/drivers/infiniband/hw/cxgb4
diff --git a/drivers/infiniband/hw/amso1100
diff --git a/drivers/infiniband/hw/mthca
diff --git a/drivers/infiniband/hw/qib
diff --git a/drivers/infiniband/hw/cxgb3
diff --git a/drivers/infiniband/ulp
diff --git a/drivers/infiniband/ulp/ipoib
diff --git a/drivers/infiniband/ulp/iser
diff --git a/drivers/infiniband/ulp/srpt
diff --git a/drivers/infiniband/ulp/srp
diff --git a/drivers/message
diff --git a/drivers/message/i2o
diff --git a/drivers/message/fusion
diff --git a/drivers/message/fusion/lsi
diff --git a/drivers/sn
diff --git a/drivers/spmi
diff --git a/drivers/eisa
diff --git a/drivers/hwmon
diff --git a/drivers/hwmon/pmbus
diff --git a/drivers/char
diff --git a/drivers/char/ipmi
diff --git a/drivers/char/hw_random
diff --git a/drivers/char/tpm
diff --git a/drivers/char/tpm/tpmd_dev
diff --git a/drivers/char/agp
diff --git a/drivers/char/diag
diff --git a/drivers/char/mwave
diff --git a/drivers/char/xilinx_hwicap
diff --git a/drivers/char/pcmcia
diff --git a/drivers/mmc
diff --git a/drivers/mmc/core
diff --git a/drivers/mmc/card
diff --git a/drivers/mmc/host
diff --git a/drivers/media
diff --git a/drivers/media/common
diff --git a/drivers/media/common/tuners
diff --git a/drivers/media/rc
diff --git a/drivers/media/rc/keymaps
diff --git a/drivers/media/tdmb
diff --git a/drivers/media/tdmb/mtv319
diff --git a/drivers/media/tdmb/fc8050
diff --git a/drivers/media/tdmb/fc8080
diff --git a/drivers/media/dvb
diff --git a/drivers/media/dvb/pt1
diff --git a/drivers/media/dvb/frontends
diff --git a/drivers/media/dvb/pluto2
diff --git a/drivers/media/dvb/dvb-core
diff --git a/drivers/media/dvb/siano
diff --git a/drivers/media/dvb/dm1105
diff --git a/drivers/media/dvb/ttpci
diff --git a/drivers/media/dvb/ddbridge
diff --git a/drivers/media/dvb/firewire
diff --git a/drivers/media/dvb/bt8xx
diff --git a/drivers/media/dvb/dvb-usb
diff --git a/drivers/media/dvb/ngene
diff --git a/drivers/media/dvb/mantis
diff --git a/drivers/media/dvb/ttusb-dec
diff --git a/drivers/media/dvb/b2c2
diff --git a/drivers/media/dvb/ttusb-budget
diff --git a/drivers/media/video
diff --git a/drivers/media/video/pwc
diff --git a/drivers/media/video/s5p-jpeg
diff --git a/drivers/media/video/tm6000
diff --git a/drivers/media/video/uvc
diff --git a/drivers/media/video/cx231xx
diff --git a/drivers/media/video/saa7134
diff --git a/drivers/media/video/gspca
diff --git a/drivers/media/video/gspca/gl860
diff --git a/drivers/media/video/gspca/stv06xx
diff --git a/drivers/media/video/gspca/m5602
diff --git a/drivers/media/video/au0828
diff --git a/drivers/media/video/marvell-ccic
diff --git a/drivers/media/video/saa7164
diff --git a/drivers/media/video/et61x251
diff --git a/drivers/media/video/cpia2
diff --git a/drivers/media/video/tlg2300
diff --git a/drivers/media/video/cx25840
diff --git a/drivers/media/video/s5p-g2d
diff --git a/drivers/media/video/s5p-tv
diff --git a/drivers/media/video/bt8xx
diff --git a/drivers/media/video/em28xx
diff --git a/drivers/media/video/cx25821
diff --git a/drivers/media/video/cx23885
diff --git a/drivers/media/video/cx88
diff --git a/drivers/media/video/s5p-fimc
diff --git a/drivers/media/video/pvrusb2
diff --git a/drivers/media/video/s5p-mfc
diff --git a/drivers/media/video/hdpvr
diff --git a/drivers/media/video/m5mols
diff --git a/drivers/media/video/cx18
diff --git a/drivers/media/video/davinci
diff --git a/drivers/media/video/usbvision
diff --git a/drivers/media/video/sn9c102
diff --git a/drivers/media/video/ivtv
diff --git a/drivers/media/video/omap3isp
diff --git a/drivers/media/video/omap
diff --git a/drivers/media/video/blackfin
diff --git a/drivers/media/video/zoran
diff --git a/drivers/media/isdbtmm
diff --git a/drivers/media/radio
diff --git a/drivers/media/radio/wl128x
diff --git a/drivers/media/radio/si470x
diff --git a/drivers/media/isdbt
diff --git a/drivers/media/isdbt/fc8300_spi
diff --git a/drivers/media/isdbt/fc8300
diff --git a/drivers/media/isdbt/fc8150_spi
diff --git a/drivers/media/isdbt/fc8150
diff --git a/drivers/media/mtv
diff --git a/drivers/media/mtv/mtv222
diff --git a/drivers/media/mtv/fc8300
diff --git a/drivers/media/mtv/mtv23x
diff --git a/drivers/media/mtv/fc8150
diff --git a/drivers/media/platform
diff --git a/drivers/media/platform/msm
diff --git a/drivers/media/platform/msm/vidc
diff --git a/drivers/media/platform/msm/dvb
diff --git a/drivers/media/platform/msm/dvb/adapter
diff --git a/drivers/media/platform/msm/dvb/demux
diff --git a/drivers/media/platform/msm/dvb/video
diff --git a/drivers/media/platform/msm/dvb/include
diff --git a/drivers/media/platform/msm/wfd
diff --git a/drivers/media/platform/msm/camera_v2
diff --git a/drivers/media/platform/msm/camera_v2/jpeg_10
diff --git a/drivers/media/platform/msm/camera_v2/sensor
diff --git a/drivers/media/platform/msm/camera_v2/sensor/flash
diff --git a/drivers/media/platform/msm/camera_v2/sensor/io
diff --git a/drivers/media/platform/msm/camera_v2/sensor/eeprom
diff --git a/drivers/media/platform/msm/camera_v2/sensor/cci
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csiphy
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csiphy/include
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csiphy/include/csi2.0
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csiphy/include/csi3.0
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csid
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csid/include
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csid/include/csi2.0
diff --git a/drivers/media/platform/msm/camera_v2/sensor/csid/include/csi3.0
diff --git a/drivers/media/platform/msm/camera_v2/sensor/actuator
diff --git a/drivers/media/platform/msm/camera_v2/msm_buf_mgr
diff --git a/drivers/media/platform/msm/camera_v2/camera
diff --git a/drivers/media/platform/msm/camera_v2/ispif
diff --git a/drivers/media/platform/msm/camera_v2/isp
diff --git a/drivers/media/platform/msm/camera_v2/pproc
diff --git a/drivers/media/platform/msm/camera_v2/pproc/cpp
diff --git a/drivers/media/platform/msm/camera_v2/msm_vb2
diff --git a/drivers/media/platform/msm/vcap
diff --git a/drivers/hsi
diff --git a/drivers/hsi/clients
diff --git a/drivers/w1
diff --git a/drivers/w1/slaves
diff --git a/drivers/w1/masters
diff --git a/drivers/connector
diff --git a/drivers/sfi
diff --git a/drivers/memstick
diff --git a/drivers/memstick/core
diff --git a/drivers/memstick/host
diff --git a/drivers/rtc
diff --git a/drivers/bluetooth
diff --git a/drivers/virtio
diff --git a/drivers/extcon
diff --git a/drivers/s390
diff --git a/drivers/s390/block
diff --git a/drivers/s390/scsi
diff --git a/drivers/s390/net
diff --git a/drivers/s390/cio
diff --git a/drivers/s390/char
diff --git a/drivers/s390/crypto
diff --git a/drivers/s390/kvm
diff --git a/drivers/zorro
diff --git a/drivers/macintosh
diff --git a/drivers/macintosh/ams
diff --git a/drivers/oprofile
diff --git a/drivers/rpmsg
diff --git a/drivers/regulator
diff --git a/drivers/crypto
diff --git a/drivers/crypto/amcc
diff --git a/drivers/crypto/caam
diff --git a/drivers/crypto/msm
diff --git a/drivers/lguest
diff --git a/drivers/lguest/x86
diff --git a/drivers/adsp_factory
diff --git a/drivers/firmware
diff --git a/drivers/firmware/google
diff --git a/drivers/watchdog
diff --git a/drivers/gpio
diff --git a/drivers/leds
diff --git a/drivers/base
diff --git a/drivers/base/regmap
diff --git a/drivers/base/power
diff --git a/drivers/pci
diff --git a/drivers/pci/hotplug
diff --git a/drivers/pci/pcie
diff --git a/drivers/pci/pcie/aer
diff --git a/drivers/dca
diff --git a/drivers/nfc
diff --git a/drivers/nfc/secnfc
diff --git a/drivers/pcmcia
diff --git a/drivers/ps3
diff --git a/drivers/tc
diff --git a/drivers/nubus
diff --git a/drivers/power
diff --git a/drivers/clocksource
diff --git a/drivers/devfreq
diff --git a/drivers/ptp
diff --git a/drivers/sh
diff --git a/drivers/sh/clk
diff --git a/drivers/sh/maple
diff --git a/drivers/sh/superhyway
diff --git a/drivers/sh/intc
diff --git a/drivers/hv
diff --git a/drivers/acpi
diff --git a/drivers/acpi/apei
diff --git a/drivers/acpi/acpica
diff --git a/drivers/hwspinlock
diff --git a/drivers/vlynq
diff --git a/drivers/motor
diff --git a/drivers/sensorhub
diff --git a/drivers/sensorhub/stm_hestia
diff --git a/drivers/sensorhub/stm_hestia/factory
diff --git a/drivers/sensorhub/stm_patek
diff --git a/drivers/sensorhub/stm_patek/factory
diff --git a/drivers/sensorhub/stm32f
diff --git a/drivers/sensorhub/stm32f/factory
diff --git a/drivers/sensorhub/atmel
diff --git a/drivers/sensorhub/atmel/factory
diff --git a/drivers/sensorhub/stm
diff --git a/drivers/sensorhub/stm/factory
diff --git a/drivers/tty
diff --git a/drivers/tty/ipwireless
diff --git a/drivers/tty/serial
diff --git a/drivers/tty/serial/jsm
diff --git a/drivers/tty/serial/cpm_uart
diff --git a/drivers/tty/serial/8250
diff --git a/drivers/tty/vt
diff --git a/drivers/tty/hvc
diff --git a/drivers/misc
diff --git a/drivers/misc/dualwave
diff --git a/drivers/misc/altera-stapl
diff --git a/drivers/misc/c2port
diff --git a/drivers/misc/eeprom
diff --git a/drivers/misc/carma
diff --git a/drivers/misc/ibmasm
diff --git a/drivers/misc/modem_if
diff --git a/drivers/misc/iwmc3200top
diff --git a/drivers/misc/sgi-gru
diff --git a/drivers/misc/cb710
diff --git a/drivers/misc/lis3lv02d
diff --git a/drivers/misc/sgi-xp
diff --git a/drivers/misc/ti-st
diff --git a/drivers/irda
diff --git a/drivers/idle
diff --git a/drivers/iommu
diff --git a/drivers/cpuidle
diff --git a/drivers/cpuidle/governors
diff --git a/drivers/edac
diff --git a/drivers/secfilter
diff --git a/drivers/pinctrl
diff --git a/drivers/accessibility
diff --git a/drivers/accessibility/braille
diff --git a/drivers/uio
diff --git a/drivers/platform
diff --git a/drivers/platform/msm
diff --git a/drivers/platform/msm/sps
diff --git a/drivers/platform/msm/ipa
diff --git a/drivers/platform/x86
diff --git a/drivers/barcode_emul
diff --git a/init
diff --git a/security
diff --git a/security/sdp
diff --git a/security/integrity
diff --git a/security/integrity/evm
diff --git a/security/integrity/ima
diff --git a/security/yama
diff --git a/security/tomoyo
diff --git a/security/selinux
diff --git a/security/selinux/ss
diff --git a/security/selinux/include
diff --git a/security/apparmor
diff --git a/security/apparmor/include
diff --git a/security/tima_uevent
diff --git a/security/smack
diff --git a/security/keys
diff --git a/security/keys/encrypted-keys
diff --git a/net
diff --git a/net/decnet
diff --git a/net/decnet/netfilter
diff --git a/net/ceph
diff --git a/net/ceph/crush
diff --git a/net/mac80211
diff --git a/net/dns_resolver
diff --git a/net/econet
diff --git a/net/sunrpc
diff --git a/net/sunrpc/xprtrdma
diff --git a/net/sunrpc/auth_gss
diff --git a/net/ipx
diff --git a/net/core
diff --git a/net/ipv4
diff --git a/net/ipv4/netfilter
diff --git a/net/netfilter
diff --git a/net/netfilter/interceptor
diff --git a/net/netfilter/ipvs
diff --git a/net/netfilter/ipset
diff --git a/net/appletalk
diff --git a/net/wimax
diff --git a/net/9p
diff --git a/net/dcb
diff --git a/net/unix
diff --git a/net/rfkill
diff --git a/net/sctp
diff --git a/net/atm
diff --git a/net/phonet
diff --git a/net/packet
diff --git a/net/rds
diff --git a/net/802
diff --git a/net/wireless
diff --git a/net/bridge
diff --git a/net/bridge/netfilter
diff --git a/net/ethernet
diff --git a/net/caif
diff --git a/net/l2tp
diff --git a/net/rose
diff --git a/net/ax25
diff --git a/net/ieee802154
diff --git a/net/wanrouter
diff --git a/net/key
diff --git a/net/xfrm
diff --git a/net/tipc
diff --git a/net/x25
diff --git a/net/sched
diff --git a/net/iucv
diff --git a/net/openvswitch
diff --git a/net/can
diff --git a/net/bluetooth
diff --git a/net/bluetooth/cmtp
diff --git a/net/bluetooth/bnep
diff --git a/net/bluetooth/rfcomm
diff --git a/net/bluetooth/hidp
diff --git a/net/8021q
diff --git a/net/dsa
diff --git a/net/lapb
diff --git a/net/nfc
diff --git a/net/nfc/llcp
diff --git a/net/nfc/nci
diff --git a/net/netlink
diff --git a/net/netlabel
diff --git a/net/llc
diff --git a/net/irda
diff --git a/net/irda/irnet
diff --git a/net/irda/ircomm
diff --git a/net/irda/irlan
diff --git a/net/batman-adv
diff --git a/net/dccp
diff --git a/net/dccp/ccids
diff --git a/net/dccp/ccids/lib
diff --git a/net/netrom
diff --git a/net/ipv6
diff --git a/net/ipv6/netfilter
diff --git a/net/rxrpc
diff --git a/virt
diff --git a/virt/kvm
diff --git a/ipc
diff --git a/Documentation
diff --git a/Documentation/ko_KR
diff --git a/Documentation/EDID
diff --git a/Documentation/mn10300
diff --git a/Documentation/devicetree
diff --git a/Documentation/devicetree/bindings
diff --git a/Documentation/devicetree/bindings/ufs
diff --git a/Documentation/devicetree/bindings/gpu
diff --git a/Documentation/devicetree/bindings/dma
diff --git a/Documentation/devicetree/bindings/dma/sps
diff --git a/Documentation/devicetree/bindings/usb
diff --git a/Documentation/devicetree/bindings/coresight
diff --git a/Documentation/devicetree/bindings/cache
diff --git a/Documentation/devicetree/bindings/nvec
diff --git a/Documentation/devicetree/bindings/qdsp
diff --git a/Documentation/devicetree/bindings/slimbus
diff --git a/Documentation/devicetree/bindings/input
diff --git a/Documentation/devicetree/bindings/input/touchscreen
diff --git a/Documentation/devicetree/bindings/input/touchscreen/gt9xx
diff --git a/Documentation/devicetree/bindings/input/misc
diff --git a/Documentation/devicetree/bindings/mtd
diff --git a/Documentation/devicetree/bindings/ata
diff --git a/Documentation/devicetree/bindings/power_supply
diff --git a/Documentation/devicetree/bindings/bif
diff --git a/Documentation/devicetree/bindings/serial
diff --git a/Documentation/devicetree/bindings/prng
diff --git a/Documentation/devicetree/bindings/pinmux
diff --git a/Documentation/devicetree/bindings/pil
diff --git a/Documentation/devicetree/bindings/spi
diff --git a/Documentation/devicetree/bindings/net
diff --git a/Documentation/devicetree/bindings/net/wireless
diff --git a/Documentation/devicetree/bindings/net/wireless/ath
diff --git a/Documentation/devicetree/bindings/net/can
diff --git a/Documentation/devicetree/bindings/powerpc
diff --git a/Documentation/devicetree/bindings/powerpc/fsl
diff --git a/Documentation/devicetree/bindings/powerpc/fsl/cpm_qe
diff --git a/Documentation/devicetree/bindings/powerpc/fsl/cpm_qe/qe
diff --git a/Documentation/devicetree/bindings/powerpc/fsl/cpm_qe/cpm
diff --git a/Documentation/devicetree/bindings/powerpc/nintendo
diff --git a/Documentation/devicetree/bindings/powerpc/4xx
diff --git a/Documentation/devicetree/bindings/thermal
diff --git a/Documentation/devicetree/bindings/fb
diff --git a/Documentation/devicetree/bindings/bt-fm
diff --git a/Documentation/devicetree/bindings/i2c
diff --git a/Documentation/devicetree/bindings/mfd
diff --git a/Documentation/devicetree/bindings/qseecom
diff --git a/Documentation/devicetree/bindings/spmi
diff --git a/Documentation/devicetree/bindings/hwmon
diff --git a/Documentation/devicetree/bindings/mmc
diff --git a/Documentation/devicetree/bindings/media
diff --git a/Documentation/devicetree/bindings/media/video
diff --git a/Documentation/devicetree/bindings/wcnss
diff --git a/Documentation/devicetree/bindings/sound
diff --git a/Documentation/devicetree/bindings/rtc
diff --git a/Documentation/devicetree/bindings/bluetooth
diff --git a/Documentation/devicetree/bindings/virtio
diff --git a/Documentation/devicetree/bindings/regulator
diff --git a/Documentation/devicetree/bindings/crypto
diff --git a/Documentation/devicetree/bindings/crypto/msm
diff --git a/Documentation/devicetree/bindings/c6x
diff --git a/Documentation/devicetree/bindings/watchdog
diff --git a/Documentation/devicetree/bindings/gpio
diff --git a/Documentation/devicetree/bindings/leds
diff --git a/Documentation/devicetree/bindings/pci
diff --git a/Documentation/devicetree/bindings/nfc
diff --git a/Documentation/devicetree/bindings/power
diff --git a/Documentation/devicetree/bindings/arm
diff --git a/Documentation/devicetree/bindings/arm/msm
diff --git a/Documentation/devicetree/bindings/arm/msm/acpuclock
diff --git a/Documentation/devicetree/bindings/arm/exynos
diff --git a/Documentation/devicetree/bindings/arm/tegra
diff --git a/Documentation/devicetree/bindings/arm/omap
diff --git a/Documentation/devicetree/bindings/batterydata
diff --git a/Documentation/devicetree/bindings/ocmem
diff --git a/Documentation/devicetree/bindings/pwm
diff --git a/Documentation/devicetree/bindings/x86
diff --git a/Documentation/devicetree/bindings/tty
diff --git a/Documentation/devicetree/bindings/tty/serial
diff --git a/Documentation/devicetree/bindings/misc
diff --git a/Documentation/devicetree/bindings/serio
diff --git a/Documentation/devicetree/bindings/iommu
diff --git a/Documentation/devicetree/bindings/pinctrl
diff --git a/Documentation/devicetree/bindings/uio
diff --git a/Documentation/devicetree/bindings/platform
diff --git a/Documentation/devicetree/bindings/platform/msm
diff --git a/Documentation/usb
diff --git a/Documentation/auxdisplay
diff --git a/Documentation/development-process
diff --git a/Documentation/frv
diff --git a/Documentation/wimax
diff --git a/Documentation/cris
diff --git a/Documentation/fault-injection
diff --git a/Documentation/input
diff --git a/Documentation/cpu-freq
diff --git a/Documentation/prctl
diff --git a/Documentation/sparc
diff --git a/Documentation/mtd
diff --git a/Documentation/mtd/devices
diff --git a/Documentation/cgroups
diff --git a/Documentation/ata
diff --git a/Documentation/laptops
diff --git a/Documentation/device-mapper
diff --git a/Documentation/rapidio
diff --git a/Documentation/i2o
diff --git a/Documentation/cdrom
diff --git a/Documentation/pps
diff --git a/Documentation/isdn
diff --git a/Documentation/block
diff --git a/Documentation/driver-model
diff --git a/Documentation/early-userspace
diff --git a/Documentation/serial
diff --git a/Documentation/telephony
diff --git a/Documentation/security
diff --git a/Documentation/m68k
diff --git a/Documentation/virtual
diff --git a/Documentation/virtual/uml
diff --git a/Documentation/virtual/kvm
diff --git a/Documentation/dvb
diff --git a/Documentation/scsi
diff --git a/Documentation/spi
diff --git a/Documentation/powerpc
diff --git a/Documentation/thermal
diff --git a/Documentation/fb
diff --git a/Documentation/sysctl
diff --git a/Documentation/target
diff --git a/Documentation/i2c
diff --git a/Documentation/i2c/muxes
diff --git a/Documentation/i2c/busses
diff --git a/Documentation/parisc
diff --git a/Documentation/vDSO
diff --git a/Documentation/scheduler
diff --git a/Documentation/hid
diff --git a/Documentation/trace
diff --git a/Documentation/trace/postprocess
diff --git a/Documentation/ide
diff --git a/Documentation/infiniband
diff --git a/Documentation/hwmon
diff --git a/Documentation/mmc
diff --git a/Documentation/vm
diff --git a/Documentation/video4linux
diff --git a/Documentation/video4linux/bttv
diff --git a/Documentation/video4linux/cx88
diff --git a/Documentation/video4linux/cx2341x
diff --git a/Documentation/aoe
diff --git a/Documentation/w1
diff --git a/Documentation/w1/slaves
diff --git a/Documentation/w1/masters
diff --git a/Documentation/namespaces
diff --git a/Documentation/connector
diff --git a/Documentation/sound
diff --git a/Documentation/sound/oss
diff --git a/Documentation/sound/alsa
diff --git a/Documentation/sound/alsa/soc
diff --git a/Documentation/sound/alsa/compress
diff --git a/Documentation/accounting
diff --git a/Documentation/ABI
diff --git a/Documentation/ABI/stable
diff --git a/Documentation/ABI/removed
diff --git a/Documentation/ABI/obsolete
diff --git a/Documentation/ABI/testing
diff --git a/Documentation/s390
diff --git a/Documentation/DocBook
diff --git a/Documentation/DocBook/media
diff --git a/Documentation/DocBook/media/v4l
diff --git a/Documentation/DocBook/media/dvb
diff --git a/Documentation/crypto
diff --git a/Documentation/crypto/msm
diff --git a/Documentation/ja_JP
diff --git a/Documentation/mips
diff --git a/Documentation/zh_CN
diff --git a/Documentation/watchdog
diff --git a/Documentation/watchdog/src
diff --git a/Documentation/networking
diff --git a/Documentation/networking/timestamping
diff --git a/Documentation/networking/caif
diff --git a/Documentation/networking/mac80211_hwsim
diff --git a/Documentation/leds
diff --git a/Documentation/timers
diff --git a/Documentation/nfc
diff --git a/Documentation/firmware_class
diff --git a/Documentation/pcmcia
diff --git a/Documentation/PCI
diff --git a/Documentation/netlabel
diff --git a/Documentation/power
diff --git a/Documentation/power/regulator
diff --git a/Documentation/misc-devices
diff --git a/Documentation/ptp
diff --git a/Documentation/sh
diff --git a/Documentation/filesystems
diff --git a/Documentation/filesystems/nfs
diff --git a/Documentation/filesystems/caching
diff --git a/Documentation/filesystems/pohmelfs
diff --git a/Documentation/filesystems/configfs
diff --git a/Documentation/acpi
diff --git a/Documentation/acpi/apei
diff --git a/Documentation/arm
diff --git a/Documentation/arm/Samsung
diff --git a/Documentation/arm/OMAP
diff --git a/Documentation/arm/msm
diff --git a/Documentation/arm/VFP
diff --git a/Documentation/arm/SPEAr
diff --git a/Documentation/arm/pxa
diff --git a/Documentation/arm/SA1100
diff --git a/Documentation/arm/nwfpe
diff --git a/Documentation/arm/SH-Mobile
diff --git a/Documentation/arm/Samsung-S3C24XX
diff --git a/Documentation/console
diff --git a/Documentation/x86
diff --git a/Documentation/x86/i386
diff --git a/Documentation/x86/x86_64
diff --git a/Documentation/pti
diff --git a/Documentation/blackfin
diff --git a/Documentation/ioctl
diff --git a/Documentation/cpuidle
diff --git a/Documentation/ia64
diff --git a/Documentation/blockdev
diff --git a/Documentation/blockdev/drbd
diff --git a/Documentation/backlight
diff --git a/Documentation/kdump
diff --git a/Documentation/make
diff --git a/Documentation/kbuild
diff --git a/Documentation/RCU
diff --git a/lib
diff --git a/lib/raid6
diff --git a/lib/raid6/test
diff --git a/lib/lzo
diff --git a/lib/zlib_inflate
diff --git a/lib/reed_solomon
diff --git a/lib/zlib_deflate
diff --git a/lib/mpi
diff --git a/lib/xz
diff --git a/samples
diff --git a/samples/uhid
diff --git a/samples/trace_events
diff --git a/samples/hw_breakpoint
diff --git a/samples/tracepoints
diff --git a/samples/kobject
diff --git a/samples/kprobes
diff --git a/samples/kfifo
diff --git a/samples/rpmsg
diff --git a/samples/hidraw
diff --git a/samples/kdb
diff --git a/mxramdisk
diff --git a/mxramdisk/sys
diff --git a/mxramdisk/proc
diff --git a/mxramdisk/system
diff --git a/mxramdisk/data
diff --git a/mxramdisk/sbin
diff --git a/mxramdisk/dev
diff --git a/sound
diff --git a/sound/core
diff --git a/sound/core/oss
diff --git a/sound/core/seq
diff --git a/sound/core/seq/oss
diff --git a/sound/usb
diff --git a/sound/usb/caiaq
diff --git a/sound/usb/usx2y
diff --git a/sound/usb/6fire
diff --git a/sound/usb/misc
diff --git a/sound/sparc
diff --git a/sound/ppc
diff --git a/sound/drivers
diff --git a/sound/drivers/opl3
diff --git a/sound/drivers/pcsp
diff --git a/sound/drivers/vx
diff --git a/sound/drivers/opl4
diff --git a/sound/drivers/mpu401
diff --git a/sound/oss
diff --git a/sound/oss/dmasound
diff --git a/sound/spi
diff --git a/sound/isa
diff --git a/sound/isa/sb
diff --git a/sound/isa/es1688
diff --git a/sound/isa/cs423x
diff --git a/sound/isa/wss
diff --git a/sound/isa/wavefront
diff --git a/sound/isa/galaxy
diff --git a/sound/isa/ad1816a
diff --git a/sound/isa/gus
diff --git a/sound/isa/msnd
diff --git a/sound/isa/ad1848
diff --git a/sound/isa/opti9xx
diff --git a/sound/soc
diff --git a/sound/soc/mid-x86
diff --git a/sound/soc/jz4740
diff --git a/sound/soc/samsung
diff --git a/sound/soc/txx9
diff --git a/sound/soc/ep93xx
diff --git a/sound/soc/codecs
diff --git a/sound/soc/codecs/audience
diff --git a/sound/soc/mxs
diff --git a/sound/soc/msm
diff --git a/sound/soc/msm/qdsp6v2
diff --git a/sound/soc/msm/qdsp6
diff --git a/sound/soc/nuc900
diff --git a/sound/soc/pxa
diff --git a/sound/soc/fsl
diff --git a/sound/soc/tegra
diff --git a/sound/soc/atmel
diff --git a/sound/soc/davinci
diff --git a/sound/soc/sh
diff --git a/sound/soc/au1x
diff --git a/sound/soc/s6000
diff --git a/sound/soc/omap
diff --git a/sound/soc/blackfin
diff --git a/sound/soc/kirkwood
diff --git a/sound/soc/imx
diff --git a/sound/firewire
diff --git a/sound/i2c
diff --git a/sound/i2c/other
diff --git a/sound/synth
diff --git a/sound/synth/emux
diff --git a/sound/parisc
diff --git a/sound/aoa
diff --git a/sound/aoa/core
diff --git a/sound/aoa/codecs
diff --git a/sound/aoa/fabrics
diff --git a/sound/aoa/soundbus
diff --git a/sound/aoa/soundbus/i2sbus
diff --git a/sound/mips
diff --git a/sound/atmel
diff --git a/sound/pci
diff --git a/sound/pci/mixart
diff --git a/sound/pci/korg1212
diff --git a/sound/pci/rme9652
diff --git a/sound/pci/au88x0
diff --git a/sound/pci/ymfpci
diff --git a/sound/pci/hda
diff --git a/sound/pci/ali5451
diff --git a/sound/pci/pcxhr
diff --git a/sound/pci/trident
diff --git a/sound/pci/cs5535audio
diff --git a/sound/pci/ac97
diff --git a/sound/pci/lola
diff --git a/sound/pci/oxygen
diff --git a/sound/pci/lx6464es
diff --git a/sound/pci/nm256
diff --git a/sound/pci/aw2
diff --git a/sound/pci/vx222
diff --git a/sound/pci/asihpi
diff --git a/sound/pci/ca0106
diff --git a/sound/pci/ctxfi
diff --git a/sound/pci/riptide
diff --git a/sound/pci/cs46xx
diff --git a/sound/pci/cs46xx/imgs
diff --git a/sound/pci/ice1712
diff --git a/sound/pci/echoaudio
diff --git a/sound/pci/emu10k1
diff --git a/sound/pcmcia
diff --git a/sound/pcmcia/vx
diff --git a/sound/pcmcia/pdaudiocf
diff --git a/sound/sh
diff --git a/sound/arm
diff --git a/tools
diff --git a/tools/usb
diff --git a/tools/dtbtool
diff --git a/tools/libmincrypt
diff --git a/tools/libmincrypt/mincrypt
diff --git a/tools/firewire
diff --git a/tools/vm
diff --git a/tools/perf
diff --git a/tools/perf/bench
diff --git a/tools/perf/util
diff --git a/tools/perf/util/scripting-engines
diff --git a/tools/perf/util/ui
diff --git a/tools/perf/util/ui/browsers
diff --git a/tools/perf/util/gtk
diff --git a/tools/perf/util/include
diff --git a/tools/perf/util/include/asm
diff --git a/tools/perf/util/include/linux
diff --git a/tools/perf/python
diff --git a/tools/perf/scripts
diff --git a/tools/perf/scripts/python
diff --git a/tools/perf/scripts/python/Perf-Trace-Util
diff --git a/tools/perf/scripts/python/Perf-Trace-Util/lib
diff --git a/tools/perf/scripts/python/Perf-Trace-Util/lib/Perf
diff --git a/tools/perf/scripts/python/Perf-Trace-Util/lib/Perf/Trace
diff --git a/tools/perf/scripts/python/bin
diff --git a/tools/perf/scripts/perl
diff --git a/tools/perf/scripts/perl/Perf-Trace-Util
diff --git a/tools/perf/scripts/perl/Perf-Trace-Util/lib
diff --git a/tools/perf/scripts/perl/Perf-Trace-Util/lib/Perf
diff --git a/tools/perf/scripts/perl/Perf-Trace-Util/lib/Perf/Trace
diff --git a/tools/perf/scripts/perl/bin
diff --git a/tools/perf/arch
diff --git a/tools/perf/arch/sparc
diff --git a/tools/perf/arch/sparc/util
diff --git a/tools/perf/arch/powerpc
diff --git a/tools/perf/arch/powerpc/util
diff --git a/tools/perf/arch/s390
diff --git a/tools/perf/arch/s390/util
diff --git a/tools/perf/arch/sh
diff --git a/tools/perf/arch/sh/util
diff --git a/tools/perf/arch/arm
diff --git a/tools/perf/arch/arm/util
diff --git a/tools/perf/arch/x86
diff --git a/tools/perf/arch/x86/util
diff --git a/tools/perf/config
diff --git a/tools/perf/Documentation
diff --git a/tools/samcrap
diff --git a/tools/nfsd
diff --git a/tools/virtio
diff --git a/tools/virtio/vhost_test
diff --git a/tools/virtio/linux
diff --git a/tools/testing
diff --git a/tools/testing/ktest
diff --git a/tools/testing/selftests
diff --git a/tools/testing/selftests/vm
diff --git a/tools/testing/selftests/breakpoints
diff --git a/tools/lguest
diff --git a/tools/power
diff --git a/tools/power/cpupower
diff --git a/tools/power/cpupower/utils
diff --git a/tools/power/cpupower/utils/idle_monitor
diff --git a/tools/power/cpupower/utils/helpers
diff --git a/tools/power/cpupower/bench
diff --git a/tools/power/cpupower/po
diff --git a/tools/power/cpupower/lib
diff --git a/tools/power/cpupower/man
diff --git a/tools/power/cpupower/debug
diff --git a/tools/power/cpupower/debug/kernel
diff --git a/tools/power/cpupower/debug/i386
diff --git a/tools/power/cpupower/debug/x86_64
diff --git a/tools/power/x86
diff --git a/tools/power/x86/x86_energy_perf_policy
diff --git a/tools/power/x86/turbostat
diff --git a/tools/hv
diff --git a/tools/include
diff --git a/tools/include/tools
diff --git a/tools/mkbootimg
diff --git a/crypto
diff --git a/crypto/async_tx
diff --git a/fs
diff --git a/fs/sysv
diff --git a/fs/ubifs
diff --git a/fs/ceph
diff --git a/fs/nls
diff --git a/fs/ufs
diff --git a/fs/afs
diff --git a/fs/logfs
diff --git a/fs/nfs_common
diff --git a/fs/fscache
diff --git a/fs/hppfs
diff --git a/fs/9p
diff --git a/fs/lockd
diff --git a/fs/ntfs
diff --git a/fs/reiserfs
diff --git a/fs/scfs
diff --git a/fs/pstore
diff --git a/fs/fuse
diff --git a/fs/hostfs
diff --git a/fs/cramfs
diff --git a/fs/notify
diff --git a/fs/notify/fanotify
diff --git a/fs/notify/dnotify
diff --git a/fs/notify/inotify
diff --git a/fs/omfs
diff --git a/fs/devpts
diff --git a/fs/ext3
diff --git a/fs/hugetlbfs
diff --git a/fs/sysfs
diff --git a/fs/debugfs
diff --git a/fs/jbd2
diff --git a/fs/befs
diff --git a/fs/hfs
diff --git a/fs/ncpfs
diff --git a/fs/cachefiles
diff --git a/fs/jffs2
diff --git a/fs/exofs
diff --git a/fs/ecryptfs
diff --git a/fs/isofs
diff --git a/fs/quota
diff --git a/fs/bfs
diff --git a/fs/efs
diff --git a/fs/qnx6
diff --git a/fs/gfs2
diff --git a/fs/btrfs
diff --git a/fs/openpromfs
diff --git a/fs/hpfs
diff --git a/fs/squashfs
diff --git a/fs/affs
diff --git a/fs/adfs
diff --git a/fs/cifs
diff --git a/fs/freevxfs
diff --git a/fs/nfsd
diff --git a/fs/exportfs
diff --git a/fs/exfat
diff --git a/fs/nfs
diff --git a/fs/nfs/blocklayout
diff --git a/fs/nfs/objlayout
diff --git a/fs/hfsplus
diff --git a/fs/proc
diff --git a/fs/fat
diff --git a/fs/coda
diff --git a/fs/romfs
diff --git a/fs/ext4
diff --git a/fs/autofs4
diff --git a/fs/sdcardfs
diff --git a/fs/dlm
diff --git a/fs/ext2
diff --git a/fs/jbd
diff --git a/fs/xfs
diff --git a/fs/jfs
diff --git a/fs/nilfs2
diff --git a/fs/udf
diff --git a/fs/qnx4
diff --git a/fs/yaffs2
diff --git a/fs/ocfs2
diff --git a/fs/ocfs2/cluster
diff --git a/fs/ocfs2/dlmfs
diff --git a/fs/ocfs2/dlm
diff --git a/fs/minix
diff --git a/fs/ramfs
diff --git a/fs/configfs
diff --git a/firmware
diff --git a/firmware/keyspan_pda
diff --git a/firmware/es325
diff --git a/firmware/matrox
diff --git a/firmware/av7110
diff --git a/firmware/tsp_stm
diff --git a/firmware/keyspan
diff --git a/firmware/advansys
diff --git a/firmware/ice40xx
diff --git a/firmware/tsp_melfas
diff --git a/firmware/tsp_melfas/victor
diff --git a/firmware/tsp_melfas/lt
diff --git a/firmware/tsp_melfas/s3
diff --git a/firmware/yam
diff --git a/firmware/cis
diff --git a/firmware/adaptec
diff --git a/firmware/emi26
diff --git a/firmware/tsp_atmel
diff --git a/firmware/vicam
diff --git a/firmware/bnx2
diff --git a/firmware/tsp_synaptics
diff --git a/firmware/tsp_synaptics/jsglte
diff --git a/firmware/tsp_synaptics/jactive
diff --git a/firmware/cpia2
diff --git a/firmware/tkey
diff --git a/firmware/acenic
diff --git a/firmware/emi62
diff --git a/firmware/edgeport
diff --git a/firmware/abov
diff --git a/firmware/dabusb
diff --git a/firmware/korg
diff --git a/firmware/epen
diff --git a/firmware/3com
diff --git a/firmware/r128
diff --git a/firmware/sb16
diff --git a/firmware/dsp56k
diff --git a/firmware/kaweth
diff --git a/firmware/e100
diff --git a/firmware/sun
diff --git a/firmware/myricom
diff --git a/firmware/qlogic
diff --git a/firmware/ositech
diff --git a/firmware/tehuti
diff --git a/firmware/yamaha
diff --git a/firmware/bnx2x
diff --git a/firmware/tigon
diff --git a/firmware/radeon
diff --git a/firmware/ttusb-budget
diff --git a/firmware/ess
diff --git a/firmware/cxgb3
diff --git a/usr
diff --git a/include
diff --git a/include/asm-generic
diff --git a/include/asm-generic/bitops
diff --git a/include/sdp
diff --git a/include/mtd
diff --git a/include/xen
diff --git a/include/xen/interface
diff --git a/include/xen/interface/io
diff --git a/include/xen/interface/hvm
diff --git a/include/math-emu
diff --git a/include/scsi
diff --git a/include/scsi/fc
diff --git a/include/net
diff --git a/include/net/netfilter
diff --git a/include/net/netfilter/ipv4
diff --git a/include/net/netfilter/ipv6
diff --git a/include/net/9p
diff --git a/include/net/sctp
diff --git a/include/net/tc_act
diff --git a/include/net/netns
diff --git a/include/net/phonet
diff --git a/include/net/caif
diff --git a/include/net/iucv
diff --git a/include/net/bluetooth
diff --git a/include/net/nfc
diff --git a/include/net/irda
diff --git a/include/target
diff --git a/include/video
diff --git a/include/trace
diff --git a/include/trace/events
diff --git a/include/media
diff --git a/include/media/msm
diff --git a/include/media/davinci
diff --git a/include/media/blackfin
diff --git a/include/uapi
diff --git a/include/uapi/media
diff --git a/include/uapi/linux
diff --git a/include/sound
diff --git a/include/crypto
diff --git a/include/crypto/internal
diff --git a/include/drm
diff --git a/include/drm/i2c
diff --git a/include/drm/ttm
diff --git a/include/pcmcia
diff --git a/include/keys
diff --git a/include/acpi
diff --git a/include/acpi/platform
diff --git a/include/rdma
diff --git a/include/misc
diff --git a/include/linux
diff --git a/include/linux/ceph
diff --git a/include/linux/sunrpc
diff --git a/include/linux/usb
diff --git a/include/linux/netfilter
diff --git a/include/linux/netfilter/ipset
diff --git a/include/linux/slimbus
diff --git a/include/linux/wimax
diff --git a/include/linux/battery
diff --git a/include/linux/battery/fuelgauge
diff --git a/include/linux/battery/charger
diff --git a/include/linux/input
diff --git a/include/linux/bcma
diff --git a/include/linux/lockd
diff --git a/include/linux/mtd
diff --git a/include/linux/mlx4
diff --git a/include/linux/tc_act
diff --git a/include/linux/tc_ematch
diff --git a/include/linux/uwb
diff --git a/include/linux/sensor
diff --git a/include/linux/bif
diff --git a/include/linux/hdlc
diff --git a/include/linux/isdn
diff --git a/include/linux/amba
diff --git a/include/linux/byteorder
diff --git a/include/linux/caif
diff --git a/include/linux/decompress
diff --git a/include/linux/dvb
diff --git a/include/linux/unaligned
diff --git a/include/linux/spi
diff --git a/include/linux/netfilter_ipv4
diff --git a/include/linux/fsl
diff --git a/include/linux/crush
diff --git a/include/linux/i2c
diff --git a/include/linux/mfd
diff --git a/include/linux/mfd/s5m87xx
diff --git a/include/linux/mfd/da9052
diff --git a/include/linux/mfd/pm8xxx
diff --git a/include/linux/mfd/wm8994
diff --git a/include/linux/mfd/wm831x
diff --git a/include/linux/mfd/wm8350
diff --git a/include/linux/mfd/pcf50633
diff --git a/include/linux/mfd/wcd9xxx
diff --git a/include/linux/mfd/abx500
diff --git a/include/linux/netfilter_arp
diff --git a/include/linux/ssb
diff --git a/include/linux/mmc
diff --git a/include/linux/hsi
diff --git a/include/linux/can
diff --git a/include/linux/can/platform
diff --git a/include/linux/nfsd
diff --git a/include/linux/rtc
diff --git a/include/linux/platform_data
diff --git a/include/linux/netfilter_ipv6
diff --git a/include/linux/raid
diff --git a/include/linux/regulator
diff --git a/include/linux/nfc
diff --git a/include/linux/power
diff --git a/include/linux/netfilter_bridge
diff --git a/include/linux/pinctrl
diff --git a/include/linux/qpnp
diff --git a/include/rxrpc
