#!/bin/bash

patch -p1 -R < "/root/mn3lite/patches/0030-turn-off-hotness.patch"
patch -p1 -R < "/root/mn3lite/patches//0029-finish-the-headers-for-int-fix-snd_soc_read-write.patch"
patch -p1 -R < "/root/mn3lite/patches//0028-a-few-more-little-tweak-fixes-and-tryout-samp-hotnes.patch"
patch -p1 -R < "/root/mn3lite/patches//0027-a-few-tweaks-from-before.patch"
patch -p1 -R < "/root/mn3lite/patches//0026-mxconfig-disable-some-more-debugging-options-and-try.patch"
patch -p1 -R < "/root/mn3lite/patches//0025-remove-extracted-zip-folder.patch"
patch -p1 -R < "/root/mn3lite/patches//0024-a-few-more-tweaks-to-crypto-hmac-script.patch"
patch -p1 -R < "/root/mn3lite/patches//0023-ensure-we-set-set_output_buffers-binfo-buffer-info-t.patch"
patch -p1 -R < "/root/mn3lite/patches//0022-cleanup-fips_crypto_hmac.sh-a-bit.patch"
patch -p1 -R < "/root/mn3lite/patches//0021-inits-in-mdss.patch"
patch -p1 -R < "/root/mn3lite/patches//0020-locally-disable-the-initialization-warning-in-stm32-.patch"
patch -p1 -R < "/root/mn3lite/patches//0019-fs-journal-fix.patch"
patch -p1 -R < "/root/mn3lite/patches//0018-fix-one-in-wcd-core.patch"
patch -p1 -R < "/root/mn3lite/patches//0017-fix-some-uninits-in-tuners.patch"
patch -p1 -R < "/root/mn3lite/patches//0016-fix-missing-initializations-in-namespace.patch"
patch -p1 -R < "/root/mn3lite/patches//0015-warn-me-on-maybe-uninitialized-shit.patch"
patch -p1 -R < "/root/mn3lite/patches//0014-revert-flar-mdss-patch.patch"
