#!/bin/bash

_repquote() {
	echo $1 | sed 's/[]\/()$*.^|[]/\\&/g'
}

pc_replace() {
	PATTERN=$(_repquote "$1")
	CONTENT=$(_repquote "$2")
	sed -i "s/$PATTERN/$CONTENT/" $3
	[ "$?" -eq "0" ] || echo "ERROR: Sed could not find string to replace"
}

pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_dev.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_debug.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_firmware.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88920.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88920.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/temphumidity_shtc1.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_ak8963c.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88922.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88005.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_cm36651.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/pressure_bmp182.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6500.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_atuc128l5har.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_yas532.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6500.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6050.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/sensors_core.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_i2c.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_c12sd.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ad7146.c"

pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88920.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88920.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/temphumidity_shtc1.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_ak8963c.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88005.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_cm36651.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_at32uc3l0128.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_lsm330.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6050.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/pressure_bmp182.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6500.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_atuc128l5har.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_yas532.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_lsm330.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6500.c"
pc_replace "pr_info" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6050.c"

pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_dev.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_debug.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_firmware.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88920.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88920.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/temphumidity_shtc1.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_ak8963c.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88922.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88005.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_cm36651.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/pressure_bmp182.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6500.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_atuc128l5har.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_yas532.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6500.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6050.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/sensors_core.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_i2c.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ssp_c12sd.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/ad7146.c"

pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gesture_max88920.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88920.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/temphumidity_shtc1.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_ak8963c.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_max88005.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/prox_cm36651.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_at32uc3l0128.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_lsm330.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6050.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/pressure_bmp182.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_mpu6500.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/mcu_atuc128l5har.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/magnetic_yas532.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/accel_lsm330.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6500.c"
pc_replace "pr_err" "pr_debug" "/root/mn3lite/drivers/sensorhub/stm32f/factory/gyro_mpu6050.c"
