#!/system/bin/sh

if [ "$1" = "headphoneleft" ]
then
    if [ -n "$2" ]
    then
        busybox echo $2 $(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2) > /sys/kernel/sound_control/headphone_gain
    fi
    busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
elif [ "$1" = "headphoneright" ]
then
    if [ -n "$2" ]
    then
        busybox echo $(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1) $2 > /sys/kernel/sound_control/headphone_gain
    fi
    busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
elif [ "$1" = "speaker_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/speaker_gain
    fi
    busybox cat /sys/kernel/sound_control/speaker_gain
elif [ "$1" = "iir1_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir1_gain
    fi
    busybox cat /sys/kernel/sound_control/iir1_gain
elif [ "$1" = "iir2_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir2_gain
    fi
    busybox cat /sys/kernel/sound_control/iir2_gain
elif [ "$1" = "usepagain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/hph_pa_enabled
    fi
    busybox cat /sys/kernel/sound_control/hph_pa_enabled
elif [ "$1" = "pagainleft" ]
then
    if [ -n "$2" ]
    then
        busybox echo $2 $(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2) > /sys/kernel/sound_control/hph_poweramp_gain
    fi
    busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1
elif [ "$1" = "pagainright" ]
then
    if [ -n "$2" ]
    then
        busybox echo $(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1) $2 > /sys/kernel/sound_control/hph_poweramp_gain
    fi
    busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2
elif [ "$1" = "highperfmode" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/high_perf_mode
    fi
    busybox cat /sys/kernel/sound_control/high_perf_mode
elif [ "$1" = "uhqamode" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/uhqa_mode
    fi
    busybox cat /sys/kernel/sound_control/uhqa_mode
elif [ "$1" = "autochopper" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/autochopper
    fi
    busybox cat /sys/kernel/sound_control/autochopper
elif [ "$1" = "chopbypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/chopper_bypass
    fi
    busybox cat /sys/kernel/sound_control/chopper_bypass
elif [ "$1" = "bypass_static_pa" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/bypass_static_pa
    fi
    busybox cat /sys/kernel/sound_control/bypass_static_pa
elif [ "$1" = "anc_delay" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/anc_delay
    fi
    busybox cat /sys/kernel/sound_control/anc_delay
elif [ "$1" = "headphone_hpf_bypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/headphone_hpf_bypass
    fi
    busybox cat /sys/kernel/sound_control/headphone_hpf_bypass
elif [ "$1" = "speaker_hpf_bypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/speaker_hpf_bypass
    fi
    busybox cat /sys/kernel/sound_control/speaker_hpf_bypass
elif [ "$1" = "interpolator_boost" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/interpolator_boost
    fi
    busybox cat /sys/kernel/sound_control/interpolator_boost
elif [ "$1" = "compander_gain_lock" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/compander_gain_lock
    fi
    busybox cat /sys/kernel/sound_control/compander_gain_lock
elif [ "$1" = "compander_gain_boost" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/compander_gain_boost
    fi
    busybox cat /sys/kernel/sound_control/compander_gain_boost
elif [ "$1" = "hpfdefault" ]
then
    if [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "headphone_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            busybox echo "0" > /sys/kernel/sound_control/headphone_hpf_cutoff
        elif [ "$2" = "75" ]
        then
            busybox echo "1" > /sys/kernel/sound_control/headphone_hpf_cutoff
        elif [ "$2" = "150" ]
        then
            busybox echo "2" > /sys/kernel/sound_control/headphone_hpf_cutoff
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "spkhpfdefault" ]
then
    if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "speaker_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            busybox echo "0" > /sys/kernel/sound_control/speaker_hpf_cutoff
        elif [ "$2" = "75" ]
        then
            busybox echo "1" > /sys/kernel/sound_control/speaker_hpf_cutoff
        elif [ "$2" = "150" ]
        then
            busybox echo "2" > /sys/kernel/sound_control/speaker_hpf_cutoff
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "peak_det_timeout" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/peak_det_timeout
    fi
    busybox cat /sys/kernel/sound_control/peak_det_timeout
elif [ "$1" = "rms_meter_div_fact" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/rms_meter_div_fact
    fi
    busybox cat /sys/kernel/sound_control/rms_meter_div_fact
elif [ "$1" = "rms_meter_resamp_fact" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/rms_meter_resamp_fact
    fi
    busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact
elif [ "$1" = "hph_pa_bias" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/hph_pa_bias
    fi
    busybox cat /sys/kernel/sound_control/hph_pa_bias
elif [ "$1" = "compander1" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/compander1
elif [ "$1" = "hph_status" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/hph_status
elif [ "$1" = "autochopper_raw" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/autochopper_raw
elif [ "$1" = "chopper" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/chopper
fi
