obj-$(CONFIG_MSM_KGSL) += gpu_sysfs_main.o gpu_sysfs_util.o gpu_sysfs_target_kgsl.o

GPU_SYSFS_TARGET_FILE_DEFINED=1

clean:
	rm -f *.o .*.cmd modules.order Module.symvers gpu_sysfs.ko gpu_sysfs.mod.c
	rm -rf .tmp_versions
