#!/system/bin/sh

echo 0 > /sys/fs/selinux/enforce
#chmod 666 /sys/block/mmcblk0/queue/scheduler
#chmod 666 /sys/block/mmcblk0rpmb/queue/scheduler
#chmod 666 /sys/block/mmcblk1/queue/scheduler
#echo "deadline" > /sys/block/mmcblk0/queue/scheduler
#echo "deadline" > /sys/block/mmcblk1/queue/scheduler
#echo "cfq" > /sys/block/mmcblk0rpmb/queue/scheduler
#echo '64' > /sys/block/mmcblk0/queue/read_ahead_kb
#echo '64' > /sys/block/mmcblk0rpmb/queue/read_ahead_kb
#echo '64' > /sys/block/mmcblk1/queue/read_ahead_kb
#echo "conservative" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
#echo "conservative" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor
#echo "conservative" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor
#echo "conservative" > /sys/devices/system/cpu/cpu3/cpufreq/scaling_governor
#echo 0 > /sys/module/cpu_boost/parameters/input_boost_ms
#echo 0 > /sys/module/cpu_boost/parameters/input_boost_freq
#echo 0 > /sys/module/cpu_boost/parameters/sync_threshold
#echo 0 > /sys/module/cpu_boost/parameters/boost_ms
#echo 0 > /sys/class/power_supply/battery/wc_enable
#echo 16384 > /proc/sys/net/netfilter/nf_conntrack_expect_max
for MYBLOCK in mmcblk0 mmcblk0rpmb mmcblk1
do
echo 0 > "/sys/block/$MYBLOCK/queue/add_random"
#echo 0 > "/sys/block/$MYBLOCK/queue/iostats"
#echo 0 > "/sys/block/$MYBLOCK/queue/iosched/slice_idle"
done
for BLOCK in /sys/block/*/queue/rotational
do
echo 0 > $BLOCK
done
echo 1 > /proc/sys/vm/panic_on_oom
#echo 0 > /proc/sys/kernel/randomize_va_space
#echo 0 > /proc/sys/kernel/sched_tunable_scaling
#echo 1 > /proc/sys/kernel/ftrace_dump_on_oops
#echo 0 > /proc/sys/net/bridge/bridge-nf-call-arptables
#echo 0 > /proc/sys/net/bridge/bridge-nf-call-ip6tables
#echo 0 > /proc/sys/net/bridge/bridge-nf-call-iptables
#echo 6 > /sys/kernel/sound_control_3/gpl_headphone_gain
#echo 6 > /sys/kernel/sound_control_3/gpl_speaker_gain
echo 0 > /sys/kernel/debug/tracing/tracing_on
echo 0 > /sys/kernel/debug/tracing/tracing_enabled
#echo f > /sys/class/net/wlan0/queues/rx-0/rps_cpus
#echo f > /sys/class/net/wlan0/queues/tx-0/xps_cpus
#echo 0 > /sys/class/net/wlan0/queues/tx-0/byte_queue_limits/hold_time
#echo 2 > /sys/class/mdnie/mdnie/scenario
#echo 0 > /sys/devices/virtual/graphics/fb0/csc_cfg
#chown 0:0 /sys/devices/virtual/graphics/fb0/csc_cfg
#chmod 400 /sys/devices/virtual/graphics/fb0/csc_cfg
#for i in $(ps -A | grep init | grep subcontext | awk '{print $1}'); do echo -1000 > /proc/$i/oom_score_adj && echo -17 > /proc/$i/oom_adj; done

#magiskpolicy --live "permissive audio_data_file audio_prop audioserver default_android_service dolby_prop dts_data_file init mediaserver platform_app priv_app property_socket su system_app system_data_file system_file system_prop system_server tmpfs untrusted_app"

#magiskpolicy --live "allow audioserver audioserver_tmpfs file { read write execute }"

#magiskpolicy --live "allow mediaserver mediaserver_tmpfs file { read write execute }"

#magiskpolicy --live "allow priv_app default_android_service service_manager { find }"

#magiskpolicy --live "allow priv_app init unix_stream_socket { connectto }"

#magiskpolicy --live "allow priv_app property_socket sock_file { write }"

#echo '1' > /sys/kernel/mdnie_control/hijack
#echo '20' > /sys/kernel/mdnie_control/offset/offset_black
#echo '1267200' > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
#echo '1267200' > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq
#echo '1267200' > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq
#echo '1267200' > /sys/devices/system/cpu/cpu3/cpufreq/scaling_min_freq
#echo '0' > /sys/kernel/gamma_control/gcontrol_gradient_enabled
#echo '1' > /sys/class/mdnie/mdnie/mode
#echo '1' > /sys/kernel/mdnie_control/hijack
#echo '0' > /sys/kernel/mdnie_control/offset_mode
#echo '1' > /sys/kernel/mdnie_control/bypass
#echo '0' > /sys/kernel/mdnie_control/sharpen_dark
#echo '0' > /sys/kernel/mdnie_control/sharpen_light
#echo '0' > /sys/kernel/mdnie_control/gamma
#echo '0' > /sys/kernel/mdnie_control/chroma
#echo '30 25 20' > /sys/kernel/mdnie_control/override/black
#echo '20 20 15' > /sys/kernel/mdnie_control/override/black
echo '0' > /sys/devices/platform/kcal_ctrl.0/kcal_enable
#echo '245' > /sys/devices/platform/kcal_ctrl.0/kcal_cont
echo '1' > /sys/devices/virtual/graphics/fb0/csc_cfg
chown 0:0 /sys/devices/virtual/graphics/fb0/csc_cfg
chmod 400 /sys/devices/virtual/graphics/fb0/csc_cfg
#echo '7' > /sys/kernel/sound_control/headphone_gain
#echo '1' > /sys/kernel/sound_control/high_perf_mode
#echo '1' > /sys/kernel/sound_control/uhqa_mode
echo 'deadline' > /sys/block/mmcblk0/queue/scheduler
echo 'deadline' > /sys/block/mmcblk1/queue/scheduler
echo '0' > /sys/devices/virtual/lcd/panel/temperature
#echo '1' > /sys/kernel/mdnie_control/bypass
echo 'y' > /sys/module/mdss_hdmi_tx/parameters/hdcp
magiskpolicy --live "permissive audio_data_file audio_prop default_android_service init default_prop platform_app property_socket system_app system_data_file system_file system_prop system_server tmpfs untrusted_app s_untrusted_app"
magiskpolicy --live "allow s_untrusted_app default_prop property_service {set}"
magiskpolicy --live "allow s_untrusted_app * property_service {set}"
#magiskpolicy --live "allow s_untrusted_app default_prop property_service set"
#am startservice com.atmos.daxappUI/com.atmos.daxappUI.DsSetProfileServices
resetprop ro.secure 0
#restorecon -R /data/media/0
#restorecon -R /data/data
#restorecon -R /data/dalvik-cache
echo 0 > /sys/fs/selinux/enforce
#echo 1 > /sys/kernel/sound_control/compander_gain_lock
#echo 0 > /sys/kernel/sound_control/compander_gain_boost
#echo 2 > /sys/kernel/sound_control/speaker_hpf_cutoff
echo 0 > /sys/devices/virtual/lcd/panel/temperature
#am startservice com.atmos/com.atmos.service.DsService

#tinymix 21 0
#tinymix 22 0
#resetprop persist.audio.mpseek 0
#resetprop persist.audio.mysound 0
#resetprop persist.audio.soundalivefxsec 0
echo '0' > /sys/kernel/sound_control/iir1_gain
echo '0' > /sys/kernel/sound_control/iir2_gain
echo '-84' > /sys/kernel/sound_control/iir1_inp2_gain
echo '-84' > /sys/kernel/sound_control/iir2_inp2_gain
#restorecon -FR /data/media/0

echo "init.d complete on $(date)" >> /mnt/sdcard/initdlog.txt
echo ' ' | tee /dev/kmsg
echo 'MACHIN3X INIT.D COMPLETED' | tee /dev/kmsg
echo ' ' | tee /dev/kmsg
exit 0
