#!/system/bin/sh

if [ "$1" = "label" ]
then
    busybox echo "Machin3x"
elif [ "$1" = "sleeptimer" ]
then
    if [ -f "/data/synapse/sleeplate.lock" ]
    then
        busybox echo "Sleeptimer already Running"
    else
        busybox echo 'RUN' > /data/synapse/sleeplate.lock
        /sbin/sleeplate &
        busybox echo "Sleeptimer Running"
    fi
elif [ "$1" = "current_now" ]
then
    busybox cat /sys/class/power_supply/battery/current_now
fi
