#!/system/bin/sh

if [ "$1" = "headphoneleft" ]
then
    LEFTVAL=$(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1)
    if [ -n "$2" ]
    then
        if [ "$2" = "$LEFTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
        else
            busybox echo $2 $(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2) > /sys/kernel/sound_control/headphone_gain
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1
    fi
elif [ "$1" = "headphoneright" ]
then
    RIGHTVAL=$(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2)
    if [ -n "$2" ]
    then
        if [ "$2" = "$RIGHTVAL" ]
        then
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
        else
            busybox echo $(busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 1) $2 > /sys/kernel/sound_control/headphone_gain
            busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
        fi
    else
        busybox cat /sys/kernel/sound_control/headphone_gain | cut -d ' ' -f 2
    fi
elif [ "$1" = "speaker_gain" ]
then
    SPKVAL=$(busybox cat /sys/kernel/sound_control/speaker_gain)
    if [ -n "$2" ]
    then
        if [ "$2" = "$SPKVAL" ]
        then
            busybox cat /sys/kernel/sound_control/speaker_gain
        else
            busybox echo "$2" > /sys/kernel/sound_control/speaker_gain
            busybox cat /sys/kernel/sound_control/speaker_gain
        fi
    else
        busybox cat /sys/kernel/sound_control/speaker_gain
    fi
elif [ "$1" = "iir1_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir1_gain
    fi
    busybox cat /sys/kernel/sound_control/iir1_gain
elif [ "$1" = "iir2_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir2_gain
    fi
    busybox cat /sys/kernel/sound_control/iir2_gain
elif [ "$1" = "iir1_inp2_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir1_inp2_gain
    fi
    busybox cat /sys/kernel/sound_control/iir1_inp2_gain
elif [ "$1" = "iir2_inp2_gain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/iir2_inp2_gain
    fi
    busybox cat /sys/kernel/sound_control/iir2_inp2_gain
elif [ "$1" = "usepagain" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/hph_pa_enabled
    fi
    busybox cat /sys/kernel/sound_control/hph_pa_enabled
elif [ "$1" = "force_hph_pa" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/force_hph_pa
    fi
    busybox cat /sys/kernel/sound_control/force_hph_pa
elif [ "$1" = "pagainleft" ]
then
    if [ -n "$2" ]
    then
        busybox echo $2 $(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2) > /sys/kernel/sound_control/hph_poweramp_gain
    fi
    busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1
elif [ "$1" = "pagainright" ]
then
    if [ -n "$2" ]
    then
        busybox echo $(busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 1) $2 > /sys/kernel/sound_control/hph_poweramp_gain
    fi
    busybox cat /sys/kernel/sound_control/hph_poweramp_gain | cut -d ' ' -f 2
elif [ "$1" = "highperfmode" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/high_perf_mode
    fi
    busybox cat /sys/kernel/sound_control/high_perf_mode
elif [ "$1" = "uhqamode" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/uhqa_mode
    fi
    busybox cat /sys/kernel/sound_control/uhqa_mode
elif [ "$1" = "autochopper" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/autochopper
    fi
    busybox cat /sys/kernel/sound_control/autochopper
elif [ "$1" = "chopbypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/chopper_bypass
    fi
    busybox cat /sys/kernel/sound_control/chopper_bypass
elif [ "$1" = "bypass_static_pa" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/bypass_static_pa
    fi
    busybox cat /sys/kernel/sound_control/bypass_static_pa
elif [ "$1" = "anc_delay" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/anc_delay
    fi
    busybox cat /sys/kernel/sound_control/anc_delay
elif [ "$1" = "headphone_left_hpf_bypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/headphone_left_hpf_bypass
    fi
    busybox cat /sys/kernel/sound_control/headphone_left_hpf_bypass
elif [ "$1" = "headphone_right_hpf_bypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/headphone_right_hpf_bypass
    fi
    busybox cat /sys/kernel/sound_control/headphone_right_hpf_bypass
elif [ "$1" = "speaker_hpf_bypass" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/speaker_hpf_bypass
    fi
    busybox cat /sys/kernel/sound_control/speaker_hpf_bypass
elif [ "$1" = "interpolator_boost" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/interpolator_boost
    fi
    busybox cat /sys/kernel/sound_control/interpolator_boost
elif [ "$1" = "compander_gain_lock" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/compander_gain_lock
    fi
    busybox cat /sys/kernel/sound_control/compander_gain_lock
elif [ "$1" = "compander_gain_boost" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/compander_gain_boost
    fi
    busybox cat /sys/kernel/sound_control/compander_gain_boost
elif [ "$1" = "wavegen_override" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/wavegen_override
    fi
    busybox cat /sys/kernel/sound_control/wavegen_override
elif [ "$1" = "harmonic_distortion_coeffs" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/harmonic_distortion_coeffs
    fi
    busybox cat /sys/kernel/sound_control/harmonic_distortion_coeffs
elif [ "$1" = "headphone_left_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            busybox echo "0" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
        elif [ "$2" = "75" ]
        then
            busybox echo "1" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
        elif [ "$2" = "150" ]
        then
            busybox echo "2" > /sys/kernel/sound_control/headphone_left_hpf_cutoff
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_left_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "headphone_right_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            busybox echo "0" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
        elif [ "$2" = "75" ]
        then
            busybox echo "1" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
        elif [ "$2" = "150" ]
        then
            busybox echo "2" > /sys/kernel/sound_control/headphone_right_hpf_cutoff
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/headphone_right_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "speaker_hpf_cutoff" ]
then
    if [ -n "$2" ]
    then
        if [ "$2" = "4" ]
        then
            busybox echo "0" > /sys/kernel/sound_controlsecjack_state/speaker_hpf_cutoff
        elif [ "$2" = "75" ]
        then
            busybox echo "1" > /sys/kernel/sound_control/speaker_hpf_cutoff
        elif [ "$2" = "150" ]
        then
            busybox echo "2" > /sys/kernel/sound_control/speaker_hpf_cutoff
        fi
    fi

    if [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "0" ]
    then
        busybox echo "4"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "1" ]
    then
        busybox echo "75"
    elif [ "$(busybox cat /sys/kernel/sound_control/speaker_hpf_cutoff)" = "2" ]
    then
        busybox echo "150"
    fi
elif [ "$1" = "peak_det_timeout" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/peak_det_timeout
    fi
    busybox cat /sys/kernel/sound_control/peak_det_timeout
elif [ "$1" = "rms_meter_div_fact" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/rms_meter_div_fact
    fi
    busybox cat /sys/kernel/sound_control/rms_meter_div_fact
elif [ "$1" = "rms_meter_resamp_fact" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/rms_meter_resamp_fact
    fi
    busybox cat /sys/kernel/sound_control/rms_meter_resamp_fact
elif [ "$1" = "hph_pa_bias" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/hph_pa_bias
    fi
    busybox cat /sys/kernel/sound_control/hph_pa_bias
elif [ "$1" = "compander_bias" ]
then
    if [ -n "$2" ]
    then
        busybox echo "$2" > /sys/kernel/sound_control/compander_bias
    fi
    busybox cat /sys/kernel/sound_control/compander_bias
elif [ "$1" = "compander1" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/compander1
elif [ "$1" = "hph_status" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/hph_status
elif [ "$1" = "class_h_control" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/class_h_control
elif [ "$1" = "autochopper_raw" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/autochopper_raw
elif [ "$1" = "chopper" ]
then
    while read -r LINE; 
    do 
        printf "%s\n" $LINE@n;
    done < /sys/kernel/sound_control/chopper
elif [ "$1" = "show_iirs_locked" ]
then
    busybox cat /sys/kernel/sound_control/iirs_locked
elif [ "$1" = "lock_iirs_locked" ]
then
    busybox echo 1 > /sys/kernel/sound_control/iirs_locked
elif [ "$1" = "unlock_iirs_locked" ]
then
    busybox echo 0 > /sys/kernel/sound_control/iirs_locked
elif [ "$1" = "headphone_dac_enabled" ]
then
    busybox cat /sys/kernel/sound_control/headphone_dac_enabled
elif [ "$1" = "secjack_state" ]
then
    busybox cat /sys/kernel/sound_control/secjack_state
fi
