#!/system/bin/sh

if [ "$1" = "sleeptimer" ]
then
    if [ -f "/data/synapse/sleeplate.lock" ]
    then
        busybox echo "Sleeptimer already Running"
    else
        busybox echo 'RUN' > /data/synapse/sleeplate.lock
        /sbin/sleepcond &
        busybox echo "Sleeptimer Running"
    fi
elif [ "$1" = "cancelsleeptimer" ]
then
    if [ -f "/data/synapse/sleeplate.lock" ]
    then
        busybox rm "/data/synapse/sleeplate.lock"
        busybox echo "Sleeptimer Cancelled"
    else
        busybox echo "Sleeptimer Not Running"
    fi
elif [ "$1" = "stout" ]
then
    if [ ! -f "/data/synapse/stimeout" ] || [ -z "$(busybox cat /data/synapse/stimeout)" ]
    then
        busybox echo "$((60*60))" > /data/synapse/stimeout
    fi
    RAWVAL="$(busybox cat /data/synapse/stimeout)"
    CURVAL="$((RAWVAL/60))"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox echo "$CURVAL"
        elif [ -f "/data/synapse/sleeplate.lock" ]
        then
            busybox echo "$CURVAL"
        else
            NEWVAL="$2"
            busybox echo "$((NEWVAL*60))" > /data/synapse/stimeout
            NEWRAW="$(busybox cat /data/synapse/stimeout)"
            NEWCUR="$((NEWRAW/60))"
            busybox echo "$NEWCUR"
        fi
    else
        busybox echo "$CURVAL"
    fi
elif [ "$1" = "reboottimer" ]
then
    if [ -f "/data/synapse/rebootlate.lock" ]
    then
        busybox echo "Reboottimer already Running"
    else
        busybox echo 'RUN' > /data/synapse/rebootlate.lock
        /sbin/recond &
        busybox echo "Reboottimer Running"
    fi
elif [ "$1" = "cancelreboottimer" ]
then
    if [ -f "/data/synapse/rebootlate.lock" ]
    then
        busybox rm "/data/synapse/rebootlate.lock"
        busybox echo "Reboottimer Cancelled"
    else
        busybox echo "Reboottimer Not Running"
    fi
elif [ "$1" = "rtout" ]
then
    if [ ! -f "/data/synapse/rtimeout" ] || [ -z "$(busybox cat /data/synapse/rtimeout)" ]
    then
        busybox echo "$((60*60))" > /data/synapse/rtimeout
    fi
    RAWVAL="$(busybox cat /data/synapse/rtimeout)"
    CURVAL="$((RAWVAL/60))"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox echo "$CURVAL"
        elif [ -f "/data/synapse/rebootlate.lock" ]
        then
            busybox echo "$CURVAL"
        else
            NEWVAL="$2"
            busybox echo "$((NEWVAL*60))" > /data/synapse/rtimeout
            NEWRAW="$(busybox cat /data/synapse/rtimeout)"
            NEWCUR="$((NEWRAW/60))"
            busybox echo "$NEWCUR"
        fi
    else
        busybox echo "$CURVAL"
    fi
elif [ "$1" = "powerofftimer" ]
then
    if [ -f "/data/synapse/powerofflate.lock" ]
    then
        busybox echo "PowerOfftimer already Running"
    else
        busybox echo 'RUN' > /data/synapse/powerofflate.lock
        /sbin/powond &
        busybox echo "PowerOfftimer Running"
    fi
elif [ "$1" = "cancelpowerofftimer" ]
then
    if [ -f "/data/synapse/powerofflate.lock" ]
    then
        busybox rm "/data/synapse/powerofflate.lock"
        busybox echo "PowerOfftimer Cancelled"
    else
        busybox echo "PowerOfftimer Not Running"
    fi
elif [ "$1" = "ptout" ]
then
    if [ ! -f "/data/synapse/ptimeout" ] || [ -z "$(busybox cat /data/synapse/ptimeout)" ]
    then
        busybox echo "$((60*60))" > /data/synapse/ptimeout
    fi
    RAWVAL="$(busybox cat /data/synapse/ptimeout)"
    CURVAL="$((RAWVAL/60))"
    if [ -n "$2" ]
    then
        if [ "$2" = "$CURVAL" ]
        then
            busybox echo "$CURVAL"
        elif [ -f "/data/synapse/powerofflate.lock" ]
        then
            busybox echo "$CURVAL"
        else
            NEWVAL="$2"
            busybox echo "$((NEWVAL*60))" > /data/synapse/ptimeout
            NEWRAW="$(busybox cat /data/synapse/ptimeout)"
            NEWCUR="$((NEWRAW/60))"
            busybox echo "$NEWCUR"
        fi
    else
        busybox echo "$CURVAL"
    fi
fi
