#!/system/bin/sh

if [ "$1" = "dropper" ]
then
	busybox echo '3' > /proc/sys/vm/drop_caches
	busybox echo "Memory Dropped"
elif [ "$1" = "killsysui" ]
then
    SYSUIPID="$(pidof com.android.systemui)"
    if kill "$SYSUIPID"
    then
        echo "SystemUI Rebooted"
    else
        echo "SystemUI Reboot Failed"
    fi
elif [ "$1" = "killviper" ]
then
    VPPID="$(pidof com.audlabs.viperfx)"
    if kill "$VPPID"
    then
        echo "ViperFX Restarted"
    else
        echo "ViperFX Restart Failed"
    fi
fi
