#!/system/xbin/busybox sh

i="0"

if [ -f "/data/synapse/powerofflate.lock" ]
then
    while [ $i -lt 3600 ]
    do
        if [ ! -f "/data/synapse/powerofflate.lock" ]
        then
            break
        fi
        sleep 1
        i=$(( i + 1 ))
    done
fi

if [ -f "/data/synapse/powerofflate.lock" ]
then
    rm /data/synapse/powerofflate.lock
    reboot -p poweroff
fi
