#!/system/xbin/busybox sh

PTIME="0"

if [ ! -f "/data/synapse/ptimeout" ] || [ -z "$(busybox cat /data/synapse/ptimeout)" ]
then
    busybox echo "3600" > /data/synapse/ptimeout
fi

TIMEOUTVAL="$(busybox cat /data/synapse/ptimeout)"

if [ -z "$TIMEOUTVAL" ]
then
    TIMEOUTVAL="3600"
fi

if [ -f "/data/synapse/powerofflate.lock" ]
then
    while [ $PTIME -lt $TIMEOUTVAL ]
    do
        if [ ! -f "/data/synapse/powerofflate.lock" ]
        then
            break
        fi
        sleep 1
        PTIME=$(( PTIME + 1 ))
    done
fi

if [ -f "/data/synapse/powerofflate.lock" ]
then
    rm /data/synapse/powerofflate.lock
    reboot -p poweroff
fi
