#!/system/xbin/busybox sh

i="0"

if [ -f "/data/synapse/sleeplate.lock" ]
then
    while [ $i -lt 3600 ]
    do
        if [ ! -f "/data/synapse/sleeplate.lock" ]
        then
            break
        fi
        sleep 1
        i=$(( i + 1 ))
    done
fi

if [ "$(cat /sys/class/lcd/panel/panel/backlight)" = "0" ]
then
    rm /data/synapse/sleeplate.lock
elif [ -f "/data/synapse/sleeplate.lock" ]
then
    input keyevent KEYCODE_SLEEP
    rm /data/synapse/sleeplate.lock
fi

