#!/system/xbin/busybox sh

STIME="0"

if [ ! -f "/data/synapse/stimeout" ] || [ -z "$(busybox cat /data/synapse/stimeout)" ]
then
    busybox echo "3600" > /data/synapse/stimeout
fi

TIMEOUTVAL="$(busybox cat /data/synapse/stimeout)"

if [ -z "$TIMEOUTVAL" ]
then
    TIMEOUTVAL="3600"
fi

if [ -f "/data/synapse/sleeplate.lock" ]
then
    while [ $STIME -lt $TIMEOUTVAL ]
    do
        if [ ! -f "/data/synapse/sleeplate.lock" ]
        then
            break
        fi
        sleep 1
        STIME=$(( STIME + 1 ))
    done
fi

if [ "$(cat /sys/class/lcd/panel/panel/backlight)" = "0" ]
then
    rm /data/synapse/sleeplate.lock
elif [ -f "/data/synapse/sleeplate.lock" ]
then
    rm /data/synapse/sleeplate.lock
    input keyevent KEYCODE_SLEEP
fi
